------------------------------------------------------------------------------------------------------------------------
-- SPDX-FileCopyrightText: 2026 VINCENT MORIN, UBO
-- SPDX-License-Identifier: GPL-3.0-or-later
------------------------------------------------------------------------------------------------------------------------
--  Table des opcodes HX : GENEREE par outils/gen_tahx_isa a partir de la table des opcodes
--  de LLIR_hardware_support. Ne pas modifier a la main.
--  Une entree par valeur du premier octet : longueur (invariant de decodage), format du
--  complement, classe d'unite, effet de pile, usage de lvl, drapeaux.
------------------------------------------------------------------------------------------------------------------------

use work.TAHX_1_ISA.all;

				-------------------
package				TAHX_1_ISA_TABLE
is				-------------------

   constant ISA_TABLE	: isa_table_t := (
      16#00# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   1 ET
      16#01# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   2 OU
      16#02# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   3 OUX
      16#03# => (true, 1, FMT_NONE, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   4 NON
      16#04# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   5 SHL
      16#05# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   6 SHR
      16#06# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   7 SAR
      16#07# => (true, 1, FMT_NONE, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   8 CLAMP0
      16#08# => (true, 1, FMT_NONE, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--   9 NEG
      16#09# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  10 CGT
      16#0A# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  11 CLT
      16#0B# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  12 CNE
      16#0C# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  13 CEQ
      16#0D# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  14 CGE
      16#0E# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  15 CLE
      16#0F# => (true, 1, FMT_NONE, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  16 ABS
      16#10# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  17 ADD
      16#11# => (true, 1, FMT_NONE, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  18 INC
      16#12# => (true, 1, FMT_NONE, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  19 SUB
      16#13# => (true, 1, FMT_NONE, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  20 DEC
      16#14# => (true, 1, FMT_NONE, ISSUE_MUL_DIV, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  21 MUL
      16#15# => (true, 1, FMT_NONE, ISSUE_MUL_DIV, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  22 DIV
      16#16# => (true, 1, FMT_NONE, ISSUE_MUL_DIV, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  23 REMI
      16#17# => (true, 1, FMT_NONE, ISSUE_MUL_DIV, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  24 MODI
      16#18# => (true, 1, FMT_NONE, ISSUE_INTEGER, 3, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  25 UBFX
      16#19# => (true, 1, FMT_NONE, ISSUE_INTEGER, 3, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  26 SBFX
      16#1A# => (true, 1, FMT_NONE, ISSUE_INTEGER, 4, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  27 BFI
      16#1B# => ISA_RESERVE,										-- reserve
      16#1C# => (true, 1, FMT_NONE, ISSUE_MUL_DIV, 3, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  28 CVTIX
      16#1D# => (true, 1, FMT_NONE, ISSUE_MUL_DIV, 3, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  29 CVTXI
      16#1E# => ISA_RESERVE,										-- reserve
      16#1F# => ISA_RESERVE,										-- reserve
      16#20# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  30 FADD
      16#21# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  31 FSUB
      16#22# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  32 FMUL
      16#23# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  33 FDIV
      16#24# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  34 FEXP
      16#25# => (true, 1, FMT_NONE, ISSUE_FLOAT, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  35 CVTIF
      16#26# => (true, 1, FMT_NONE, ISSUE_FLOAT, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  36 CVTFI
      16#27# => (true, 1, FMT_NONE, ISSUE_FLOAT, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  37 CVTFIR
      16#28# => (true, 1, FMT_NONE, ISSUE_FLOAT, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  38 FNEG
      16#29# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  39 FCGT
      16#2A# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  40 FCLT
      16#2B# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  41 FCNE
      16#2C# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  42 FCEQ
      16#2D# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  43 FCGE
      16#2E# => (true, 1, FMT_NONE, ISSUE_FLOAT, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  44 FCLE
      16#2F# => (true, 1, FMT_NONE, ISSUE_FLOAT, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  45 FABS
      16#30# => (true, 1, FMT_NONE, ISSUE_NONE, 1, 0, STACK_DROP, LVL_NONE, false, false, false, false),	--  46 DROP
      16#31# => (true, 1, FMT_NONE, ISSUE_NONE, 1, 2, STACK_DUP, LVL_NONE, false, false, false, false),	--  47 DUP
      16#32# => (true, 1, FMT_NONE, ISSUE_NONE, 2, 3, STACK_OVER, LVL_NONE, false, false, false, false),	--  48 OVER
      16#33# => (true, 1, FMT_NONE, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	--  49 CALLI
      16#34# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 3, 0, STACK_LINEAR, LVL_NONE, false, false, true, false),	--  50 BLKMOV
      16#35# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 3, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	--  51 BLKCMP
      16#36# => ISA_RESERVE,										-- reserve
      16#37# => ISA_RESERVE,										-- reserve
      16#38# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  52 CO_VAR
      16#39# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	--  53 HEAP_ALLOC
      16#3A# => ISA_RESERVE,										-- reserve
      16#3B# => ISA_RESERVE,										-- reserve
      16#3C# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 3, 0, STACK_LINEAR, LVL_NONE, false, false, true, false),	--  54 BLKAND
      16#3D# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 3, 0, STACK_LINEAR, LVL_NONE, false, false, true, false),	--  55 BLKOU
      16#3E# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 3, 0, STACK_LINEAR, LVL_NONE, false, false, true, false),	--  56 BLKOUX
      16#3F# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 2, 0, STACK_LINEAR, LVL_NONE, false, false, true, false),	--  57 BLKNOT
      16#40# => ISA_RESERVE,										-- reserve
      16#41# => ISA_RESERVE,										-- reserve
      16#42# => ISA_RESERVE,										-- reserve
      16#43# => ISA_RESERVE,										-- reserve
      16#44# => (true, 3, FMT_B16, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_FRAME, false, false, true, true),	--  58 LINK
      16#45# => (true, 3, FMT_B16, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_FRAME, false, false, true, false),	--  59 EXC_MACH
      16#46# => ISA_RESERVE,										-- reserve
      16#47# => (true, 3, FMT_B16, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, false, false),	--  60 LVA
      16#48# => (true, 4, FMT_B24, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_FRAME, false, false, true, true),	--  61 LINK
      16#49# => (true, 4, FMT_B24, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_FRAME, false, false, true, false),	--  62 EXC_MACH
      16#4A# => ISA_RESERVE,										-- reserve
      16#4B# => (true, 4, FMT_B24, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, false, false),	--  63 LVA
      16#4C# => ISA_RESERVE,										-- reserve
      16#4D# => ISA_RESERVE,										-- reserve
      16#4E# => ISA_RESERVE,										-- reserve
      16#4F# => ISA_RESERVE,										-- reserve
      16#50# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  64 LB
      16#51# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  65 LW
      16#52# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  66 LD
      16#53# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  67 LQ
      16#54# => (true, 3, FMT_B16, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  68 LB
      16#55# => (true, 3, FMT_B16, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  69 LW
      16#56# => (true, 3, FMT_B16, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  70 LD
      16#57# => (true, 3, FMT_B16, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  71 LQ
      16#58# => (true, 4, FMT_B24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  72 LB
      16#59# => (true, 4, FMT_B24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  73 LW
      16#5A# => (true, 4, FMT_B24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  74 LD
      16#5B# => (true, 4, FMT_B24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  75 LQ
      16#5C# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	--  76 CHKB
      16#5D# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	--  77 CHKW
      16#5E# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	--  78 CHKD
      16#5F# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	--  79 CHKQ
      16#60# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  80 SB
      16#61# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  81 SW
      16#62# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  82 SD
      16#63# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  83 SQ
      16#64# => (true, 3, FMT_B16, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  84 SB
      16#65# => (true, 3, FMT_B16, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  85 SW
      16#66# => (true, 3, FMT_B16, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  86 SD
      16#67# => (true, 3, FMT_B16, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  87 SQ
      16#68# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  88 SB
      16#69# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  89 SW
      16#6A# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  90 SD
      16#6B# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  91 SQ
      16#6C# => ISA_RESERVE,										-- reserve
      16#6D# => ISA_RESERVE,										-- reserve
      16#6E# => ISA_RESERVE,										-- reserve
      16#6F# => ISA_RESERVE,										-- reserve
      16#70# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  92 ULB
      16#71# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  93 ULW
      16#72# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  94 ULD
      16#73# => ISA_RESERVE,										-- reserve
      16#74# => (true, 3, FMT_B16, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  95 ULB
      16#75# => (true, 3, FMT_B16, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  96 ULW
      16#76# => (true, 3, FMT_B16, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  97 ULD
      16#77# => ISA_RESERVE,										-- reserve
      16#78# => (true, 4, FMT_B24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  98 ULB
      16#79# => (true, 4, FMT_B24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	--  99 ULW
      16#7A# => (true, 4, FMT_B24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 100 ULD
      16#7B# => ISA_RESERVE,										-- reserve
      16#7C# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 101 CHKUB
      16#7D# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 102 CHKUW
      16#7E# => (true, 4, FMT_B24, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 103 CHKUD
      16#7F# => ISA_RESERVE,										-- reserve
      16#80# => ISA_RESERVE,										-- reserve
      16#81# => ISA_RESERVE,										-- reserve
      16#82# => ISA_RESERVE,										-- reserve
      16#83# => ISA_RESERVE,										-- reserve
      16#84# => ISA_RESERVE,										-- reserve
      16#85# => ISA_RESERVE,										-- reserve
      16#86# => ISA_RESERVE,										-- reserve
      16#87# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 104 LIVA
      16#88# => ISA_RESERVE,										-- reserve
      16#89# => ISA_RESERVE,										-- reserve
      16#8A# => ISA_RESERVE,										-- reserve
      16#8B# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 105 LIVA
      16#8C# => ISA_RESERVE,										-- reserve
      16#8D# => ISA_RESERVE,										-- reserve
      16#8E# => ISA_RESERVE,										-- reserve
      16#8F# => ISA_RESERVE,										-- reserve
      16#90# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 106 LIB
      16#91# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 107 LIW
      16#92# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 108 LID
      16#93# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 109 LIQ
      16#94# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 110 LIB
      16#95# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 111 LIW
      16#96# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 112 LID
      16#97# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 113 LIQ
      16#98# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 114 LIB
      16#99# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 115 LIW
      16#9A# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 116 LID
      16#9B# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 117 LIQ
      16#9C# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 118 CHKIB
      16#9D# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 119 CHKIW
      16#9E# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 120 CHKID
      16#9F# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 121 CHKIQ
      16#A0# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 122 SIB
      16#A1# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 123 SIW
      16#A2# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 124 SID
      16#A3# => (true, 1, FMT_NONE, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 125 SIQ
      16#A4# => (true, 4, FMT_C24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 126 SIB
      16#A5# => (true, 4, FMT_C24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 127 SIW
      16#A6# => (true, 4, FMT_C24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 128 SID
      16#A7# => (true, 4, FMT_C24, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 129 SIQ
      16#A8# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 130 SIB
      16#A9# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 131 SIW
      16#AA# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 132 SID
      16#AB# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 0, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 133 SIQ
      16#AC# => ISA_RESERVE,										-- reserve
      16#AD# => ISA_RESERVE,										-- reserve
      16#AE# => ISA_RESERVE,										-- reserve
      16#AF# => ISA_RESERVE,										-- reserve
      16#B0# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 134 ULIB
      16#B1# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 135 ULIW
      16#B2# => (true, 1, FMT_NONE, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 136 ULID
      16#B3# => ISA_RESERVE,										-- reserve
      16#B4# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 137 ULIB
      16#B5# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 138 ULIW
      16#B6# => (true, 4, FMT_C24, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 139 ULID
      16#B7# => ISA_RESERVE,										-- reserve
      16#B8# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 140 ULIB
      16#B9# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 141 ULIW
      16#BA# => (true, 5, FMT_C32, ISSUE_MEMORY, 0, 1, STACK_LINEAR, LVL_ADDR, false, false, true, false),	-- 142 ULID
      16#BB# => ISA_RESERVE,										-- reserve
      16#BC# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 143 CHKUIB
      16#BD# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 144 CHKUIW
      16#BE# => (true, 5, FMT_C32, ISSUE_MEMORY, 1, 1, STACK_KEEP_TOP, LVL_FRAME, false, false, true, false),	-- 145 CHKUID
      16#BF# => ISA_RESERVE,										-- reserve
      16#C0# => (true, 2, FMT_D8, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 146 LI
      16#C1# => (true, 3, FMT_D16, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 147 LI
      16#C2# => (true, 5, FMT_D32, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 148 LI
      16#C3# => (true, 9, FMT_D64, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 149 LI
      16#C4# => (true, 3, FMT_D8_8, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 150 UBFXI
      16#C5# => (true, 3, FMT_D8_8, ISSUE_INTEGER, 1, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 151 SBFXI
      16#C6# => (true, 3, FMT_D8_8, ISSUE_INTEGER, 2, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 152 BFII
      16#C7# => ISA_RESERVE,										-- reserve
      16#C8# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 4, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	-- 153 LEXCMPB
      16#C9# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 4, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	-- 154 LEXCMPW
      16#CA# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 4, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	-- 155 LEXCMPD
      16#CB# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 4, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	-- 156 LEXCMPQ
      16#CC# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 4, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	-- 157 ULEXCMPB
      16#CD# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 4, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	-- 158 ULEXCMPW
      16#CE# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 4, 1, STACK_LINEAR, LVL_NONE, false, false, true, false),	-- 159 ULEXCMPD
      16#CF# => ISA_RESERVE,										-- reserve
      16#D0# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D1# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D2# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D3# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D4# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D5# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D6# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D7# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D8# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#D9# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#DA# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#DB# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#DC# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#DD# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#DE# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#DF# => (true, 1, FMT_IMM4, ISSUE_INTEGER, 0, 1, STACK_LINEAR, LVL_NONE, false, false, false, false),	-- 160 LI(imm4)
      16#E0# => (true, 2, FMT_BR8, ISSUE_BRANCH, 0, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 161 BRA
      16#E1# => (true, 3, FMT_BR16, ISSUE_BRANCH, 0, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 162 BRA
      16#E2# => (true, 4, FMT_BR24, ISSUE_BRANCH, 0, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 163 BRA
      16#E3# => (true, 5, FMT_BR32, ISSUE_BRANCH, 0, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 164 BRA
      16#E4# => (true, 2, FMT_BR8, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 165 BT
      16#E5# => (true, 3, FMT_BR16, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 166 BT
      16#E6# => (true, 4, FMT_BR24, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 167 BT
      16#E7# => (true, 5, FMT_BR32, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 168 BT
      16#E8# => (true, 2, FMT_BR8, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 169 BF
      16#E9# => (true, 3, FMT_BR16, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 170 BF
      16#EA# => (true, 4, FMT_BR24, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 171 BF
      16#EB# => (true, 5, FMT_BR32, ISSUE_BRANCH, 1, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 172 BF
      16#EC# => ISA_RESERVE,										-- reserve
      16#ED# => ISA_RESERVE,										-- reserve
      16#EE# => ISA_RESERVE,										-- reserve
      16#EF# => ISA_RESERVE,										-- reserve
      16#F0# => (true, 2, FMT_D8, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_NONE, true, true, false, false),	-- 173 TRAP
      16#F1# => ISA_RESERVE,										-- reserve
      16#F2# => (true, 4, FMT_D24, ISSUE_BRANCH, 0, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 174 CALL
      16#F3# => ISA_RESERVE,										-- reserve
      16#F4# => ISA_RESERVE,										-- reserve
      16#F5# => ISA_RESERVE,										-- reserve
      16#F6# => (true, 4, FMT_D24, ISSUE_BRANCH, 0, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 175 RTD
      16#F7# => (true, 1, FMT_NONE, ISSUE_BRANCH, 0, 0, STACK_LINEAR, LVL_NONE, false, true, false, false),	-- 176 RTD
      16#F8# => (true, 2, FMT_D8, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_FRAME, false, false, true, true),	-- 177 UNLINK
      16#F9# => (true, 2, FMT_D8, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_FRAME, false, false, true, true),	-- 178 UNLINKR
      16#FA# => ISA_RESERVE,										-- reserve
      16#FB# => ISA_RESERVE,										-- reserve
      16#FC# => ISA_RESERVE,										-- reserve
      16#FD# => ISA_RESERVE,										-- reserve
      16#FE# => (true, 4, FMT_D24, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_NONE, true, true, true, false),	-- 179 EXC_RAISE
      16#FF# => (true, 1, FMT_NONE, ISSUE_COMPLEX, 0, 0, STACK_LINEAR, LVL_NONE, true, true, false, false) 	-- 180 RTX
   );

		-------------------
end package	TAHX_1_ISA_TABLE;
		-------------------
