/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module FETCH_BYTE_QUEUE(CLK_i, RESET_i, FETCH_VALID_i, FETCH_PC_i, FETCH_BLOCK_i, FETCH_COUNT_i, FETCH_FAULT_i, CONSUME_i, CONSUMED_BYTES_i, FLUSH_i, FETCH_READY_o, WINDOW_o, WINDOW_COUNT_o, WINDOW_PC_o, WINDOW_FAULT_o, EMPTY_o, BYTE_COUNT_o);
  wire _00_;
  wire [6:0] _01_;
  wire [6:0] _02_;
  wire [31:0] _03_;
  wire [6:0] _04_;
  wire [31:0] _05_;
  wire [6:0] _06_;
  wire [6:0] _07_;
  wire [31:0] _08_;
  wire [7:0] _09_;
  wire [31:0] _10_;
  wire [31:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [63:0] _15_;
  wire [63:0] _16_;
  wire [6:0] _17_;
  wire [6:0] _18_;
  wire [7:0] _19_;
  wire [63:0] _20_;
  wire _21_;
  wire _22_;
  wire [31:0] _23_;
  wire [6:0] _24_;
  wire [31:0] _25_;
  wire [6:0] _26_;
  wire [31:0] _27_;
  wire [6:0] _28_;
  wire [31:0] _29_;
  wire [6:0] _30_;
  wire [31:0] _31_;
  wire [6:0] _32_;
  wire [31:0] _33_;
  wire [6:0] _34_;
  wire [31:0] _35_;
  wire [6:0] _36_;
  wire [31:0] _37_;
  wire [6:0] _38_;
  wire [31:0] _39_;
  wire [6:0] _40_;
  wire [6:0] _41_;
  wire [31:0] _42_;
  wire [6:0] _43_;
  wire [31:0] _44_;
  wire [6:0] _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire [31:0] _49_;
  wire [5:0] _50_;
  wire _51_;
  wire [5:0] _52_;
  wire _53_;
  wire [5:0] _54_;
  wire [31:0] _55_;
  wire [6:0] _56_;
  wire [31:0] _57_;
  wire [6:0] _58_;
  wire [6:0] _59_;
  wire [31:0] _60_;
  wire [6:0] _61_;
  wire [31:0] _62_;
  wire [6:0] _63_;
  wire [31:0] _64_;
  wire [31:0] _65_;
  wire [6:0] _66_;
  wire [31:0] _67_;
  wire [6:0] _68_;
  wire [31:0] _69_;
  wire [6:0] _70_;
  wire [6:0] _71_;
  wire [31:0] _72_;
  wire [6:0] _73_;
  wire [31:0] _74_;
  wire [6:0] _75_;
  wire [31:0] _76_;
  wire [31:0] _77_;
  wire [6:0] _78_;
  wire [31:0] _79_;
  wire [6:0] _80_;
  wire [31:0] _81_;
  wire [6:0] _82_;
  wire [6:0] _83_;
  wire [31:0] _84_;
  wire [6:0] _85_;
  wire [31:0] _86_;
  output [7:0] BYTE_COUNT_o;
  wire [7:0] BYTE_COUNT_o;
  input CLK_i;
  wire CLK_i;
  input [5:0] CONSUMED_BYTES_i;
  wire [5:0] CONSUMED_BYTES_i;
  input CONSUME_i;
  wire CONSUME_i;
  output EMPTY_o;
  wire EMPTY_o;
  input [255:0] FETCH_BLOCK_i;
  wire [255:0] FETCH_BLOCK_i;
  input [5:0] FETCH_COUNT_i;
  wire [5:0] FETCH_COUNT_i;
  input FETCH_FAULT_i;
  wire FETCH_FAULT_i;
  input [63:0] FETCH_PC_i;
  wire [63:0] FETCH_PC_i;
  output FETCH_READY_o;
  wire FETCH_READY_o;
  input FETCH_VALID_i;
  wire FETCH_VALID_i;
  input FLUSH_i;
  wire FLUSH_i;
  input RESET_i;
  wire RESET_i;
  output [5:0] WINDOW_COUNT_o;
  wire [5:0] WINDOW_COUNT_o;
  output [31:0] WINDOW_FAULT_o;
  wire [31:0] WINDOW_FAULT_o;
  output [63:0] WINDOW_PC_o;
  wire [63:0] WINDOW_PC_o;
  output [255:0] WINDOW_o;
  wire [255:0] WINDOW_o;
  reg [7:0] count;
  reg [6:0] head;
  reg [63:0] head_pc;
  wire ready;
  reg [7:0] bytes [127:0];
  always @(posedge CLK_i) begin
    if (_22_)
      bytes[_56_] <= FETCH_BLOCK_i[255:248];
    if (_22_)
      bytes[_57_[6:0]] <= FETCH_BLOCK_i[247:240];
    if (_22_)
      bytes[_59_] <= FETCH_BLOCK_i[239:232];
    if (_22_)
      bytes[_60_[6:0]] <= FETCH_BLOCK_i[231:224];
    if (_22_)
      bytes[_61_] <= FETCH_BLOCK_i[223:216];
    if (_22_)
      bytes[_62_[6:0]] <= FETCH_BLOCK_i[215:208];
    if (_22_)
      bytes[_63_] <= FETCH_BLOCK_i[207:200];
    if (_22_)
      bytes[_65_[6:0]] <= FETCH_BLOCK_i[199:192];
    if (_22_)
      bytes[_66_] <= FETCH_BLOCK_i[191:184];
    if (_22_)
      bytes[_67_[6:0]] <= FETCH_BLOCK_i[183:176];
    if (_22_)
      bytes[_68_] <= FETCH_BLOCK_i[175:168];
    if (_22_)
      bytes[_69_[6:0]] <= FETCH_BLOCK_i[167:160];
    if (_22_)
      bytes[_71_] <= FETCH_BLOCK_i[159:152];
    if (_22_)
      bytes[_72_[6:0]] <= FETCH_BLOCK_i[151:144];
    if (_22_)
      bytes[_73_] <= FETCH_BLOCK_i[143:136];
    if (_22_)
      bytes[_74_[6:0]] <= FETCH_BLOCK_i[135:128];
    if (_22_)
      bytes[_75_] <= FETCH_BLOCK_i[127:120];
    if (_22_)
      bytes[_77_[6:0]] <= FETCH_BLOCK_i[119:112];
    if (_22_)
      bytes[_78_] <= FETCH_BLOCK_i[111:104];
    if (_22_)
      bytes[_79_[6:0]] <= FETCH_BLOCK_i[103:96];
    if (_22_)
      bytes[_80_] <= FETCH_BLOCK_i[95:88];
    if (_22_)
      bytes[_81_[6:0]] <= FETCH_BLOCK_i[87:80];
    if (_22_)
      bytes[_83_] <= FETCH_BLOCK_i[79:72];
    if (_22_)
      bytes[_84_[6:0]] <= FETCH_BLOCK_i[71:64];
    if (_22_)
      bytes[_85_] <= FETCH_BLOCK_i[63:56];
    if (_22_)
      bytes[_86_[6:0]] <= FETCH_BLOCK_i[55:48];
    if (_22_)
      bytes[_02_] <= FETCH_BLOCK_i[47:40];
    if (_22_)
      bytes[_03_[6:0]] <= FETCH_BLOCK_i[39:32];
    if (_22_)
      bytes[_04_] <= FETCH_BLOCK_i[31:24];
    if (_22_)
      bytes[_05_[6:0]] <= FETCH_BLOCK_i[23:16];
    if (_22_)
      bytes[_06_] <= FETCH_BLOCK_i[15:8];
    if (_22_)
      bytes[_07_] <= FETCH_BLOCK_i[7:0];
  end
  assign WINDOW_o[79:72] = bytes[_35_[6:0]];
  assign WINDOW_o[71:64] = bytes[_36_];
  assign WINDOW_o[63:56] = bytes[_37_[6:0]];
  assign WINDOW_o[55:48] = bytes[_38_];
  assign WINDOW_o[47:40] = bytes[_39_[6:0]];
  assign WINDOW_o[39:32] = bytes[_41_];
  assign WINDOW_o[255:248] = bytes[_40_];
  assign WINDOW_o[247:240] = bytes[_49_[6:0]];
  assign WINDOW_o[31:24] = bytes[_42_[6:0]];
  assign WINDOW_o[239:232] = bytes[_58_];
  assign WINDOW_o[231:224] = bytes[_64_[6:0]];
  assign WINDOW_o[223:216] = bytes[_70_];
  assign WINDOW_o[215:208] = bytes[_76_[6:0]];
  assign WINDOW_o[207:200] = bytes[_82_];
  assign WINDOW_o[199:192] = bytes[_01_];
  assign WINDOW_o[191:184] = bytes[_08_[6:0]];
  assign WINDOW_o[183:176] = bytes[_18_];
  assign WINDOW_o[175:168] = bytes[_23_[6:0]];
  assign WINDOW_o[167:160] = bytes[_24_];
  assign WINDOW_o[23:16] = bytes[_43_];
  assign WINDOW_o[159:152] = bytes[_25_[6:0]];
  assign WINDOW_o[151:144] = bytes[_26_];
  assign WINDOW_o[143:136] = bytes[_27_[6:0]];
  assign WINDOW_o[135:128] = bytes[_28_];
  assign WINDOW_o[127:120] = bytes[_29_[6:0]];
  assign WINDOW_o[119:112] = bytes[_30_];
  assign WINDOW_o[111:104] = bytes[_31_[6:0]];
  assign WINDOW_o[103:96] = bytes[_32_];
  assign WINDOW_o[95:88] = bytes[_33_[6:0]];
  assign WINDOW_o[87:80] = bytes[_34_];
  assign WINDOW_o[15:8] = bytes[_44_[6:0]];
  assign WINDOW_o[7:0] = bytes[_45_];
  reg [0:0] faults [127:0];
  always @(posedge CLK_i) begin
    if (_22_)
      faults[_56_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_57_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_59_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_60_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_61_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_62_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_63_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_65_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_66_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_67_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_68_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_69_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_71_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_72_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_73_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_74_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_75_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_77_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_78_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_79_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_80_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_81_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_83_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_84_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_85_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_86_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_02_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_03_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_04_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_05_[6:0]] <= FETCH_FAULT_i;
    if (_22_)
      faults[_06_] <= FETCH_FAULT_i;
    if (_22_)
      faults[_07_] <= FETCH_FAULT_i;
  end
  assign WINDOW_FAULT_o[9] = faults[_35_[6:0]];
  assign WINDOW_FAULT_o[8] = faults[_36_];
  assign WINDOW_FAULT_o[7] = faults[_37_[6:0]];
  assign WINDOW_FAULT_o[6] = faults[_38_];
  assign WINDOW_FAULT_o[5] = faults[_39_[6:0]];
  assign WINDOW_FAULT_o[4] = faults[_41_];
  assign WINDOW_FAULT_o[31] = faults[_40_];
  assign WINDOW_FAULT_o[30] = faults[_49_[6:0]];
  assign WINDOW_FAULT_o[3] = faults[_42_[6:0]];
  assign WINDOW_FAULT_o[29] = faults[_58_];
  assign WINDOW_FAULT_o[28] = faults[_64_[6:0]];
  assign WINDOW_FAULT_o[27] = faults[_70_];
  assign WINDOW_FAULT_o[26] = faults[_76_[6:0]];
  assign WINDOW_FAULT_o[25] = faults[_82_];
  assign WINDOW_FAULT_o[24] = faults[_01_];
  assign WINDOW_FAULT_o[23] = faults[_08_[6:0]];
  assign WINDOW_FAULT_o[22] = faults[_18_];
  assign WINDOW_FAULT_o[21] = faults[_23_[6:0]];
  assign WINDOW_FAULT_o[20] = faults[_24_];
  assign WINDOW_FAULT_o[2] = faults[_43_];
  assign WINDOW_FAULT_o[19] = faults[_25_[6:0]];
  assign WINDOW_FAULT_o[18] = faults[_26_];
  assign WINDOW_FAULT_o[17] = faults[_27_[6:0]];
  assign WINDOW_FAULT_o[16] = faults[_28_];
  assign WINDOW_FAULT_o[15] = faults[_29_[6:0]];
  assign WINDOW_FAULT_o[14] = faults[_30_];
  assign WINDOW_FAULT_o[13] = faults[_31_[6:0]];
  assign WINDOW_FAULT_o[12] = faults[_32_];
  assign WINDOW_FAULT_o[11] = faults[_33_[6:0]];
  assign WINDOW_FAULT_o[10] = faults[_34_];
  assign WINDOW_FAULT_o[1] = faults[_44_[6:0]];
  assign WINDOW_FAULT_o[0] = faults[_45_];
  assign _00_ = count <= 7'h60;
  assign _03_[6:0] = _55_[6:0] + 5'h1b;
  assign _04_ = _55_[6:0] + 5'h1c;
  assign _05_[6:0] = _55_[6:0] + 5'h1d;
  assign _06_ = _55_[6:0] + 5'h1e;
  assign _07_ = _55_[6:0] + 5'h1f;
  assign _01_ = head + 3'h7;
  assign _09_ = count - _54_;
  assign _10_[6:0] = head + _54_;
  assign _11_[7:0] = _09_ + _52_;
  assign ready = _00_ ? 1'h1 : 1'h0;
  assign _12_ = ! _09_;
  assign _13_ = _52_ > 1'h0;
  assign _14_ = _13_ & _12_;
  assign _15_ = head_pc + _54_;
  assign _16_ = _14_ ? FETCH_PC_i : _15_;
  assign _17_ = _48_ ? 7'h00 : _10_[6:0];
  assign _19_ = _48_ ? 8'h00 : _11_[7:0];
  assign _20_ = _48_ ? head_pc : _16_;
  assign _21_ = ~ _48_;
  assign _22_ = _21_ & _13_;
  assign _08_[6:0] = head + 4'h8;
  always @(posedge CLK_i)
    head <= _17_;
  always @(posedge CLK_i)
    count <= _19_;
  always @(posedge CLK_i)
    head_pc <= _20_;
  assign _18_ = head + 4'h9;
  assign _23_[6:0] = head + 4'ha;
  assign _24_ = head + 4'hb;
  assign _40_ = head + 1'h0;
  assign _25_[6:0] = head + 4'hc;
  assign _26_ = head + 4'hd;
  assign _27_[6:0] = head + 4'he;
  assign _28_ = head + 4'hf;
  assign _29_[6:0] = head + 5'h10;
  assign _30_ = head + 5'h11;
  assign _31_[6:0] = head + 5'h12;
  assign _32_ = head + 5'h13;
  assign _33_[6:0] = head + 5'h14;
  assign _34_ = head + 5'h15;
  assign _49_[6:0] = head + 1'h1;
  assign _35_[6:0] = head + 5'h16;
  assign _36_ = head + 5'h17;
  assign _37_[6:0] = head + 5'h18;
  assign _38_ = head + 5'h19;
  assign _39_[6:0] = head + 5'h1a;
  assign _41_ = head + 5'h1b;
  assign _42_[6:0] = head + 5'h1c;
  assign _43_ = head + 5'h1d;
  assign _44_[6:0] = head + 5'h1e;
  assign _45_ = head + 5'h1f;
  assign _58_ = head + 2'h2;
  assign _46_ = count > 6'h20;
  assign WINDOW_COUNT_o = _46_ ? 6'h20 : count[5:0];
  assign _47_ = ! count;
  assign EMPTY_o = _47_ ? 1'h1 : 1'h0;
  assign _48_ = RESET_i | FLUSH_i;
  assign _50_ = CONSUME_i ? CONSUMED_BYTES_i : 6'h00;
  assign _51_ = ready & FETCH_VALID_i;
  assign _52_ = _51_ ? FETCH_COUNT_i : 6'h00;
  assign _53_ = _50_ > count;
  assign _54_ = _53_ ? count[5:0] : _50_;
  assign _55_[6:0] = head + count[6:0];
  assign _56_ = _55_[6:0] + 1'h0;
  assign _57_[6:0] = _55_[6:0] + 1'h1;
  assign _59_ = _55_[6:0] + 2'h2;
  assign _60_[6:0] = _55_[6:0] + 2'h3;
  assign _61_ = _55_[6:0] + 3'h4;
  assign _64_[6:0] = head + 2'h3;
  assign _62_[6:0] = _55_[6:0] + 3'h5;
  assign _63_ = _55_[6:0] + 3'h6;
  assign _65_[6:0] = _55_[6:0] + 3'h7;
  assign _66_ = _55_[6:0] + 4'h8;
  assign _67_[6:0] = _55_[6:0] + 4'h9;
  assign _68_ = _55_[6:0] + 4'ha;
  assign _69_[6:0] = _55_[6:0] + 4'hb;
  assign _70_ = head + 3'h4;
  assign _71_ = _55_[6:0] + 4'hc;
  assign _72_[6:0] = _55_[6:0] + 4'hd;
  assign _73_ = _55_[6:0] + 4'he;
  assign _74_[6:0] = _55_[6:0] + 4'hf;
  assign _75_ = _55_[6:0] + 5'h10;
  assign _77_[6:0] = _55_[6:0] + 5'h11;
  assign _78_ = _55_[6:0] + 5'h12;
  assign _76_[6:0] = head + 3'h5;
  assign _79_[6:0] = _55_[6:0] + 5'h13;
  assign _80_ = _55_[6:0] + 5'h14;
  assign _81_[6:0] = _55_[6:0] + 5'h15;
  assign _83_ = _55_[6:0] + 5'h16;
  assign _84_[6:0] = _55_[6:0] + 5'h17;
  assign _85_ = _55_[6:0] + 5'h18;
  assign _82_ = head + 3'h6;
  assign _86_[6:0] = _55_[6:0] + 5'h19;
  assign _02_ = _55_[6:0] + 5'h1a;
  assign BYTE_COUNT_o = count;
  assign FETCH_READY_o = ready;
  assign WINDOW_PC_o = head_pc;
endmodule
