/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module FETCH_BYTE_QUEUE(CLK_i, RESET_i, FETCH_VALID_i, FETCH_PC_i, FETCH_BLOCK_i, FETCH_COUNT_i, FETCH_FAULT_i, CONSUME_i, CONSUMED_BYTES_i, FLUSH_i, FETCH_READY_o, WINDOW_o, WINDOW_COUNT_o, WINDOW_PC_o, WINDOW_FAULT_o, EMPTY_o, BYTE_COUNT_o);
  wire _000_;
  wire _001_;
  wire [1:0] _002_;
  wire [1:0] _003_;
  wire [1:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire [7:0] _009_;
  wire [6:0] _010_;
  wire [7:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [63:0] _015_;
  wire [63:0] _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire [1:0] _020_;
  wire [1:0] _021_;
  wire [1:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire [1:0] _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire [1:0] _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire [1:0] _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire [1:0] _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire [1:0] _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire [1:0] _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire [1:0] _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire [1:0] _065_;
  wire [1:0] _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire [1:0] _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire [1:0] _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire [1:0] _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [1:0] _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire [1:0] _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire [1:0] _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire [1:0] _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire [1:0] _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire [1:0] _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire [1:0] _121_;
  wire [1:0] _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire [1:0] _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire [1:0] _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire [1:0] _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire [1:0] _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire [1:0] _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire [5:0] _159_;
  wire _160_;
  wire [5:0] _161_;
  wire _162_;
  wire [5:0] _163_;
  wire _164_;
  wire _165_;
  wire [1:0] _166_;
  wire [1:0] _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire [1:0] _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire [1:0] _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire [1:0] _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire [1:0] _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire [1:0] _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire [1:0] _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire [1:0] _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire [1:0] _210_;
  wire _211_;
  wire [1:0] _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire [1:0] _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire [1:0] _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire [1:0] _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire [1:0] _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire [1:0] _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire [1:0] _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire [1:0] _251_;
  wire [1:0] _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire [1:0] _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire [1:0] _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire [1:0] _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire [1:0] _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire [1:0] _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire [1:0] _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire [1:0] _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire [1:0] _295_;
  wire [1:0] _296_;
  wire _297_;
  wire [1:0] _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire [1:0] _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire [1:0] _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire [1:0] _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire [1:0] _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire [1:0] _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire [1:0] _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire [1:0] _337_;
  wire [1:0] _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _500_;
  wire _501_;
  wire _502_;
  wire _503_;
  wire _504_;
  wire _505_;
  wire _506_;
  wire _507_;
  wire _508_;
  wire _509_;
  wire _510_;
  wire _511_;
  wire _512_;
  wire _513_;
  wire _514_;
  wire _515_;
  wire _516_;
  wire _517_;
  wire _518_;
  wire _519_;
  wire _520_;
  wire _521_;
  wire _522_;
  wire _523_;
  wire _524_;
  wire _525_;
  wire _526_;
  wire _527_;
  wire _528_;
  wire _529_;
  wire _530_;
  wire _531_;
  wire _532_;
  wire _533_;
  wire _534_;
  wire _535_;
  output [7:0] BYTE_COUNT_o;
  wire [7:0] BYTE_COUNT_o;
  input CLK_i;
  wire CLK_i;
  input [5:0] CONSUMED_BYTES_i;
  wire [5:0] CONSUMED_BYTES_i;
  input CONSUME_i;
  wire CONSUME_i;
  output EMPTY_o;
  wire EMPTY_o;
  input [255:0] FETCH_BLOCK_i;
  wire [255:0] FETCH_BLOCK_i;
  input [5:0] FETCH_COUNT_i;
  wire [5:0] FETCH_COUNT_i;
  input FETCH_FAULT_i;
  wire FETCH_FAULT_i;
  input [63:0] FETCH_PC_i;
  wire [63:0] FETCH_PC_i;
  output FETCH_READY_o;
  wire FETCH_READY_o;
  input FETCH_VALID_i;
  wire FETCH_VALID_i;
  input FLUSH_i;
  wire FLUSH_i;
  input RESET_i;
  wire RESET_i;
  output [5:0] WINDOW_COUNT_o;
  wire [5:0] WINDOW_COUNT_o;
  output [31:0] WINDOW_FAULT_o;
  wire [31:0] WINDOW_FAULT_o;
  output [63:0] WINDOW_PC_o;
  wire [63:0] WINDOW_PC_o;
  output [255:0] WINDOW_o;
  wire [255:0] WINDOW_o;
  reg [1151:0] banks;
  reg [7:0] count;
  reg [6:0] head;
  wire [6:0] head_bits;
  reg [63:0] head_pc;
  wire [287:0] rd0;
  wire [287:0] rd1;
  wire [287:0] rd2;
  wire [287:0] rd3;
  wire [287:0] rd4;
  wire [287:0] rd5;
  wire ready;
  wire [6:0] tail_bits;
  wire [6:0] tail_index;
  wire [287:0] wr0;
  wire [287:0] wr1;
  wire [287:0] wr2;
  wire [287:0] wr3;
  wire [287:0] wr4;
  wire [287:0] wr5;
  always @(posedge CLK_i)
    if (!_158_) head_pc <= _016_;
  always @(posedge CLK_i)
    if (_158_) count <= 8'h00;
    else count <= _011_;
  always @(posedge CLK_i)
    if (_158_) head <= 7'h00;
    else head <= _010_;
  always @(posedge CLK_i)
    if (_343_) banks[1124:1116] <= { FETCH_FAULT_i, wr5[286:279] };
  always @(posedge CLK_i)
    if (_344_) banks[1133:1125] <= { FETCH_FAULT_i, wr5[286:279] };
  always @(posedge CLK_i)
    if (_345_) banks[1142:1134] <= { FETCH_FAULT_i, wr5[286:279] };
  always @(posedge CLK_i)
    if (_346_) banks[1088:1080] <= { FETCH_FAULT_i, wr5[277:270] };
  always @(posedge CLK_i)
    if (_347_) banks[1097:1089] <= { FETCH_FAULT_i, wr5[277:270] };
  always @(posedge CLK_i)
    if (_348_) banks[1106:1098] <= { FETCH_FAULT_i, wr5[277:270] };
  always @(posedge CLK_i)
    if (_349_) banks[1052:1044] <= { FETCH_FAULT_i, wr5[268:261] };
  always @(posedge CLK_i)
    if (_350_) banks[1061:1053] <= { FETCH_FAULT_i, wr5[268:261] };
  always @(posedge CLK_i)
    if (_351_) banks[1070:1062] <= { FETCH_FAULT_i, wr5[268:261] };
  always @(posedge CLK_i)
    if (_352_) banks[1016:1008] <= { FETCH_FAULT_i, wr5[259:252] };
  always @(posedge CLK_i)
    if (_353_) banks[1025:1017] <= { FETCH_FAULT_i, wr5[259:252] };
  always @(posedge CLK_i)
    if (_354_) banks[1034:1026] <= { FETCH_FAULT_i, wr5[259:252] };
  always @(posedge CLK_i)
    if (_355_) banks[980:972] <= { FETCH_FAULT_i, wr5[250:243] };
  always @(posedge CLK_i)
    if (_356_) banks[989:981] <= { FETCH_FAULT_i, wr5[250:243] };
  always @(posedge CLK_i)
    if (_357_) banks[998:990] <= { FETCH_FAULT_i, wr5[250:243] };
  always @(posedge CLK_i)
    if (_358_) banks[944:936] <= { FETCH_FAULT_i, wr5[241:234] };
  always @(posedge CLK_i)
    if (_359_) banks[953:945] <= { FETCH_FAULT_i, wr5[241:234] };
  always @(posedge CLK_i)
    if (_360_) banks[962:954] <= { FETCH_FAULT_i, wr5[241:234] };
  always @(posedge CLK_i)
    if (_361_) banks[908:900] <= { FETCH_FAULT_i, wr5[232:225] };
  always @(posedge CLK_i)
    if (_362_) banks[917:909] <= { FETCH_FAULT_i, wr5[232:225] };
  always @(posedge CLK_i)
    if (_363_) banks[926:918] <= { FETCH_FAULT_i, wr5[232:225] };
  always @(posedge CLK_i)
    if (_364_) banks[872:864] <= { FETCH_FAULT_i, wr5[223:216] };
  always @(posedge CLK_i)
    if (_365_) banks[881:873] <= { FETCH_FAULT_i, wr5[223:216] };
  always @(posedge CLK_i)
    if (_366_) banks[890:882] <= { FETCH_FAULT_i, wr5[223:216] };
  always @(posedge CLK_i)
    if (_367_) banks[836:828] <= { FETCH_FAULT_i, wr5[214:207] };
  always @(posedge CLK_i)
    if (_368_) banks[845:837] <= { FETCH_FAULT_i, wr5[214:207] };
  always @(posedge CLK_i)
    if (_369_) banks[854:846] <= { FETCH_FAULT_i, wr5[214:207] };
  always @(posedge CLK_i)
    if (_370_) banks[800:792] <= { FETCH_FAULT_i, wr5[205:198] };
  always @(posedge CLK_i)
    if (_371_) banks[809:801] <= { FETCH_FAULT_i, wr5[205:198] };
  always @(posedge CLK_i)
    if (_372_) banks[818:810] <= { FETCH_FAULT_i, wr5[205:198] };
  always @(posedge CLK_i)
    if (_373_) banks[764:756] <= { FETCH_FAULT_i, wr5[196:189] };
  always @(posedge CLK_i)
    if (_374_) banks[773:765] <= { FETCH_FAULT_i, wr5[196:189] };
  always @(posedge CLK_i)
    if (_375_) banks[782:774] <= { FETCH_FAULT_i, wr5[196:189] };
  always @(posedge CLK_i)
    if (_376_) banks[728:720] <= { FETCH_FAULT_i, wr5[187:180] };
  always @(posedge CLK_i)
    if (_377_) banks[737:729] <= { FETCH_FAULT_i, wr5[187:180] };
  always @(posedge CLK_i)
    if (_378_) banks[746:738] <= { FETCH_FAULT_i, wr5[187:180] };
  always @(posedge CLK_i)
    if (_379_) banks[692:684] <= { FETCH_FAULT_i, wr5[178:171] };
  always @(posedge CLK_i)
    if (_380_) banks[701:693] <= { FETCH_FAULT_i, wr5[178:171] };
  always @(posedge CLK_i)
    if (_381_) banks[710:702] <= { FETCH_FAULT_i, wr5[178:171] };
  always @(posedge CLK_i)
    if (_382_) banks[656:648] <= { FETCH_FAULT_i, wr5[169:162] };
  always @(posedge CLK_i)
    if (_383_) banks[665:657] <= { FETCH_FAULT_i, wr5[169:162] };
  always @(posedge CLK_i)
    if (_384_) banks[674:666] <= { FETCH_FAULT_i, wr5[169:162] };
  always @(posedge CLK_i)
    if (_385_) banks[620:612] <= { FETCH_FAULT_i, wr5[160:153] };
  always @(posedge CLK_i)
    if (_386_) banks[629:621] <= { FETCH_FAULT_i, wr5[160:153] };
  always @(posedge CLK_i)
    if (_387_) banks[638:630] <= { FETCH_FAULT_i, wr5[160:153] };
  always @(posedge CLK_i)
    if (_388_) banks[584:576] <= { FETCH_FAULT_i, wr5[151:144] };
  always @(posedge CLK_i)
    if (_389_) banks[593:585] <= { FETCH_FAULT_i, wr5[151:144] };
  always @(posedge CLK_i)
    if (_390_) banks[602:594] <= { FETCH_FAULT_i, wr5[151:144] };
  always @(posedge CLK_i)
    if (_391_) banks[548:540] <= { FETCH_FAULT_i, wr5[142:135] };
  always @(posedge CLK_i)
    if (_392_) banks[557:549] <= { FETCH_FAULT_i, wr5[142:135] };
  always @(posedge CLK_i)
    if (_393_) banks[566:558] <= { FETCH_FAULT_i, wr5[142:135] };
  always @(posedge CLK_i)
    if (_394_) banks[512:504] <= { FETCH_FAULT_i, wr5[133:126] };
  always @(posedge CLK_i)
    if (_395_) banks[521:513] <= { FETCH_FAULT_i, wr5[133:126] };
  always @(posedge CLK_i)
    if (_396_) banks[530:522] <= { FETCH_FAULT_i, wr5[133:126] };
  always @(posedge CLK_i)
    if (_397_) banks[476:468] <= { FETCH_FAULT_i, wr5[124:117] };
  always @(posedge CLK_i)
    if (_398_) banks[485:477] <= { FETCH_FAULT_i, wr5[124:117] };
  always @(posedge CLK_i)
    if (_399_) banks[494:486] <= { FETCH_FAULT_i, wr5[124:117] };
  always @(posedge CLK_i)
    if (_400_) banks[440:432] <= { FETCH_FAULT_i, wr5[115:108] };
  always @(posedge CLK_i)
    if (_401_) banks[449:441] <= { FETCH_FAULT_i, wr5[115:108] };
  always @(posedge CLK_i)
    if (_402_) banks[458:450] <= { FETCH_FAULT_i, wr5[115:108] };
  always @(posedge CLK_i)
    if (_403_) banks[404:396] <= { FETCH_FAULT_i, wr5[106:99] };
  always @(posedge CLK_i)
    if (_404_) banks[413:405] <= { FETCH_FAULT_i, wr5[106:99] };
  always @(posedge CLK_i)
    if (_405_) banks[422:414] <= { FETCH_FAULT_i, wr5[106:99] };
  always @(posedge CLK_i)
    if (_406_) banks[368:360] <= { FETCH_FAULT_i, wr5[97:90] };
  always @(posedge CLK_i)
    if (_407_) banks[377:369] <= { FETCH_FAULT_i, wr5[97:90] };
  always @(posedge CLK_i)
    if (_408_) banks[386:378] <= { FETCH_FAULT_i, wr5[97:90] };
  always @(posedge CLK_i)
    if (_409_) banks[332:324] <= { FETCH_FAULT_i, wr5[88:81] };
  always @(posedge CLK_i)
    if (_410_) banks[341:333] <= { FETCH_FAULT_i, wr5[88:81] };
  always @(posedge CLK_i)
    if (_411_) banks[350:342] <= { FETCH_FAULT_i, wr5[88:81] };
  always @(posedge CLK_i)
    if (_412_) banks[296:288] <= { FETCH_FAULT_i, wr5[79:72] };
  always @(posedge CLK_i)
    if (_413_) banks[305:297] <= { FETCH_FAULT_i, wr5[79:72] };
  always @(posedge CLK_i)
    if (_414_) banks[314:306] <= { FETCH_FAULT_i, wr5[79:72] };
  always @(posedge CLK_i)
    if (_415_) banks[260:252] <= { FETCH_FAULT_i, wr5[70:63] };
  always @(posedge CLK_i)
    if (_416_) banks[269:261] <= { FETCH_FAULT_i, wr5[70:63] };
  always @(posedge CLK_i)
    if (_417_) banks[278:270] <= { FETCH_FAULT_i, wr5[70:63] };
  always @(posedge CLK_i)
    if (_418_) banks[224:216] <= { FETCH_FAULT_i, wr5[61:54] };
  always @(posedge CLK_i)
    if (_419_) banks[233:225] <= { FETCH_FAULT_i, wr5[61:54] };
  always @(posedge CLK_i)
    if (_420_) banks[242:234] <= { FETCH_FAULT_i, wr5[61:54] };
  always @(posedge CLK_i)
    if (_421_) banks[188:180] <= { FETCH_FAULT_i, wr5[52:45] };
  always @(posedge CLK_i)
    if (_422_) banks[197:189] <= { FETCH_FAULT_i, wr5[52:45] };
  always @(posedge CLK_i)
    if (_423_) banks[206:198] <= { FETCH_FAULT_i, wr5[52:45] };
  always @(posedge CLK_i)
    if (_424_) banks[152:144] <= { FETCH_FAULT_i, wr5[43:36] };
  always @(posedge CLK_i)
    if (_425_) banks[161:153] <= { FETCH_FAULT_i, wr5[43:36] };
  always @(posedge CLK_i)
    if (_426_) banks[170:162] <= { FETCH_FAULT_i, wr5[43:36] };
  always @(posedge CLK_i)
    if (_427_) banks[116:108] <= { FETCH_FAULT_i, wr5[34:27] };
  always @(posedge CLK_i)
    if (_428_) banks[125:117] <= { FETCH_FAULT_i, wr5[34:27] };
  always @(posedge CLK_i)
    if (_429_) banks[134:126] <= { FETCH_FAULT_i, wr5[34:27] };
  always @(posedge CLK_i)
    if (_430_) banks[80:72] <= { FETCH_FAULT_i, wr5[25:18] };
  always @(posedge CLK_i)
    if (_431_) banks[89:81] <= { FETCH_FAULT_i, wr5[25:18] };
  always @(posedge CLK_i)
    if (_432_) banks[98:90] <= { FETCH_FAULT_i, wr5[25:18] };
  always @(posedge CLK_i)
    if (_433_) banks[44:36] <= { FETCH_FAULT_i, wr5[16:9] };
  always @(posedge CLK_i)
    if (_434_) banks[53:45] <= { FETCH_FAULT_i, wr5[16:9] };
  always @(posedge CLK_i)
    if (_435_) banks[62:54] <= { FETCH_FAULT_i, wr5[16:9] };
  always @(posedge CLK_i)
    if (_436_) banks[8:0] <= { FETCH_FAULT_i, wr5[7:0] };
  always @(posedge CLK_i)
    if (_437_) banks[17:9] <= { FETCH_FAULT_i, wr5[7:0] };
  always @(posedge CLK_i)
    if (_438_) banks[26:18] <= { FETCH_FAULT_i, wr5[7:0] };
  always @(posedge CLK_i)
    if (_439_) banks[431:423] <= { FETCH_FAULT_i, wr5[106:99] };
  always @(posedge CLK_i)
    if (_440_) banks[791:783] <= { FETCH_FAULT_i, wr5[196:189] };
  always @(posedge CLK_i)
    if (_441_) banks[827:819] <= { FETCH_FAULT_i, wr5[205:198] };
  always @(posedge CLK_i)
    if (_442_) banks[143:135] <= { FETCH_FAULT_i, wr5[34:27] };
  always @(posedge CLK_i)
    if (_443_) banks[467:459] <= { FETCH_FAULT_i, wr5[115:108] };
  always @(posedge CLK_i)
    if (_444_) banks[503:495] <= { FETCH_FAULT_i, wr5[124:117] };
  always @(posedge CLK_i)
    if (_445_) banks[539:531] <= { FETCH_FAULT_i, wr5[133:126] };
  always @(posedge CLK_i)
    if (_446_) banks[575:567] <= { FETCH_FAULT_i, wr5[142:135] };
  always @(posedge CLK_i)
    if (_447_) banks[611:603] <= { FETCH_FAULT_i, wr5[151:144] };
  always @(posedge CLK_i)
    if (_448_) banks[647:639] <= { FETCH_FAULT_i, wr5[160:153] };
  always @(posedge CLK_i)
    if (_449_) banks[683:675] <= { FETCH_FAULT_i, wr5[169:162] };
  always @(posedge CLK_i)
    if (_450_) banks[719:711] <= { FETCH_FAULT_i, wr5[178:171] };
  always @(posedge CLK_i)
    if (_451_) banks[755:747] <= { FETCH_FAULT_i, wr5[187:180] };
  always @(posedge CLK_i)
    if (_452_) banks[863:855] <= { FETCH_FAULT_i, wr5[214:207] };
  always @(posedge CLK_i)
    if (_453_) banks[899:891] <= { FETCH_FAULT_i, wr5[223:216] };
  always @(posedge CLK_i)
    if (_454_) banks[935:927] <= { FETCH_FAULT_i, wr5[232:225] };
  always @(posedge CLK_i)
    if (_455_) banks[971:963] <= { FETCH_FAULT_i, wr5[241:234] };
  always @(posedge CLK_i)
    if (_456_) banks[1007:999] <= { FETCH_FAULT_i, wr5[250:243] };
  always @(posedge CLK_i)
    if (_457_) banks[1043:1035] <= { FETCH_FAULT_i, wr5[259:252] };
  always @(posedge CLK_i)
    if (_458_) banks[1079:1071] <= { FETCH_FAULT_i, wr5[268:261] };
  always @(posedge CLK_i)
    if (_459_) banks[1115:1107] <= { FETCH_FAULT_i, wr5[277:270] };
  always @(posedge CLK_i)
    if (_460_) banks[1151:1143] <= { FETCH_FAULT_i, wr5[286:279] };
  always @(posedge CLK_i)
    if (_461_) banks[35:27] <= { FETCH_FAULT_i, wr5[7:0] };
  always @(posedge CLK_i)
    if (_462_) banks[71:63] <= { FETCH_FAULT_i, wr5[16:9] };
  always @(posedge CLK_i)
    if (_463_) banks[107:99] <= { FETCH_FAULT_i, wr5[25:18] };
  always @(posedge CLK_i)
    if (_464_) banks[179:171] <= { FETCH_FAULT_i, wr5[43:36] };
  always @(posedge CLK_i)
    if (_465_) banks[215:207] <= { FETCH_FAULT_i, wr5[52:45] };
  always @(posedge CLK_i)
    if (_466_) banks[251:243] <= { FETCH_FAULT_i, wr5[61:54] };
  always @(posedge CLK_i)
    if (_467_) banks[287:279] <= { FETCH_FAULT_i, wr5[70:63] };
  always @(posedge CLK_i)
    if (_468_) banks[323:315] <= { FETCH_FAULT_i, wr5[79:72] };
  always @(posedge CLK_i)
    if (_469_) banks[359:351] <= { FETCH_FAULT_i, wr5[88:81] };
  always @(posedge CLK_i)
    if (_470_) banks[395:387] <= { FETCH_FAULT_i, wr5[97:90] };
  assign _503_ = ~ _158_;
  assign _504_ = ~ _491_;
  assign _505_ = ~ _481_;
  assign _506_ = ~ _480_;
  assign _507_ = ~ _499_;
  assign _508_ = ~ _490_;
  assign _509_ = ~ _489_;
  assign _510_ = ~ _488_;
  assign _511_ = ~ _487_;
  assign _512_ = ~ _486_;
  assign _513_ = ~ _485_;
  assign _514_ = ~ _484_;
  assign _515_ = ~ _483_;
  assign _516_ = ~ _482_;
  assign _517_ = ~ _479_;
  assign _518_ = ~ _478_;
  assign _519_ = ~ _477_;
  assign _520_ = ~ _476_;
  assign _521_ = ~ _475_;
  assign _522_ = ~ _474_;
  assign _523_ = ~ _473_;
  assign _524_ = ~ _472_;
  assign _525_ = ~ _471_;
  assign _526_ = ~ _502_;
  assign _527_ = ~ _501_;
  assign _528_ = ~ _500_;
  assign _529_ = ~ _498_;
  assign _530_ = ~ _497_;
  assign _531_ = ~ _496_;
  assign _532_ = ~ _495_;
  assign _533_ = ~ _494_;
  assign _534_ = ~ _493_;
  assign _535_ = ~ _492_;
  assign _343_ = & { _503_, _013_, _168_ };
  assign _344_ = & { _503_, _013_, _169_ };
  assign _345_ = & { _503_, _013_, _170_ };
  assign _346_ = & { _503_, _013_, _174_ };
  assign _347_ = & { _503_, _013_, _175_ };
  assign _348_ = & { _503_, _013_, _176_ };
  assign _349_ = & { _503_, _013_, _180_ };
  assign _350_ = & { _503_, _013_, _181_ };
  assign _351_ = & { _503_, _013_, _182_ };
  assign _352_ = & { _503_, _013_, _186_ };
  assign _353_ = & { _503_, _013_, _187_ };
  assign _354_ = & { _503_, _013_, _188_ };
  assign _355_ = & { _503_, _013_, _191_ };
  assign _356_ = & { _503_, _013_, _193_ };
  assign _357_ = & { _503_, _013_, _194_ };
  assign _358_ = & { _503_, _013_, _197_ };
  assign _359_ = & { _503_, _013_, _198_ };
  assign _360_ = & { _503_, _013_, _199_ };
  assign _361_ = & { _503_, _013_, _202_ };
  assign _362_ = & { _503_, _013_, _203_ };
  assign _363_ = & { _503_, _013_, _204_ };
  assign _364_ = & { _503_, _013_, _207_ };
  assign _365_ = & { _503_, _013_, _208_ };
  assign _366_ = & { _503_, _013_, _209_ };
  assign _367_ = & { _503_, _013_, _213_ };
  assign _368_ = & { _503_, _013_, _214_ };
  assign _369_ = & { _503_, _013_, _215_ };
  assign _370_ = & { _503_, _013_, _219_ };
  assign _371_ = & { _503_, _013_, _221_ };
  assign _372_ = & { _503_, _013_, _222_ };
  assign _373_ = & { _503_, _013_, _226_ };
  assign _374_ = & { _503_, _013_, _227_ };
  assign _375_ = & { _503_, _013_, _228_ };
  assign _376_ = & { _503_, _013_, _231_ };
  assign _377_ = & { _503_, _013_, _232_ };
  assign _378_ = & { _503_, _013_, _233_ };
  assign _379_ = & { _503_, _013_, _237_ };
  assign _380_ = & { _503_, _013_, _238_ };
  assign _381_ = & { _503_, _013_, _239_ };
  assign _382_ = & { _503_, _013_, _242_ };
  assign _383_ = & { _503_, _013_, _243_ };
  assign _384_ = & { _503_, _013_, _244_ };
  assign _385_ = & { _503_, _013_, _247_ };
  assign _386_ = & { _503_, _013_, _248_ };
  assign _387_ = & { _503_, _013_, _249_ };
  assign _388_ = & { _503_, _013_, _253_ };
  assign _389_ = & { _503_, _013_, _254_ };
  assign _390_ = & { _503_, _013_, _255_ };
  assign _391_ = & { _503_, _013_, _259_ };
  assign _392_ = & { _503_, _013_, _260_ };
  assign _393_ = & { _503_, _013_, _261_ };
  assign _394_ = & { _503_, _013_, _265_ };
  assign _395_ = & { _503_, _013_, _266_ };
  assign _396_ = & { _503_, _013_, _267_ };
  assign _397_ = & { _503_, _013_, _271_ };
  assign _398_ = & { _503_, _013_, _272_ };
  assign _399_ = & { _503_, _013_, _273_ };
  assign _400_ = & { _503_, _013_, _276_ };
  assign _401_ = & { _503_, _013_, _278_ };
  assign _402_ = & { _503_, _013_, _279_ };
  assign _403_ = & { _503_, _013_, _282_ };
  assign _404_ = & { _503_, _013_, _283_ };
  assign _405_ = & { _503_, _013_, _284_ };
  assign _406_ = & { _503_, _013_, _287_ };
  assign _407_ = & { _503_, _013_, _288_ };
  assign _408_ = & { _503_, _013_, _289_ };
  assign _409_ = & { _503_, _013_, _292_ };
  assign _410_ = & { _503_, _013_, _293_ };
  assign _411_ = & { _503_, _013_, _294_ };
  assign _412_ = & { _503_, _013_, _299_ };
  assign _413_ = & { _503_, _013_, _300_ };
  assign _414_ = & { _503_, _013_, _301_ };
  assign _415_ = & { _503_, _013_, _305_ };
  assign _416_ = & { _503_, _013_, _307_ };
  assign _417_ = & { _503_, _013_, _308_ };
  assign _418_ = & { _503_, _013_, _312_ };
  assign _419_ = & { _503_, _013_, _313_ };
  assign _420_ = & { _503_, _013_, _314_ };
  assign _421_ = & { _503_, _013_, _317_ };
  assign _422_ = & { _503_, _013_, _318_ };
  assign _423_ = & { _503_, _013_, _319_ };
  assign _424_ = & { _503_, _013_, _323_ };
  assign _425_ = & { _503_, _013_, _324_ };
  assign _426_ = & { _503_, _013_, _325_ };
  assign _427_ = & { _503_, _013_, _328_ };
  assign _428_ = & { _503_, _013_, _329_ };
  assign _429_ = & { _503_, _013_, _330_ };
  assign _430_ = & { _503_, _013_, _333_ };
  assign _431_ = & { _503_, _013_, _334_ };
  assign _432_ = & { _503_, _013_, _335_ };
  assign _433_ = & { _503_, _013_, _339_ };
  assign _434_ = & { _503_, _013_, _340_ };
  assign _435_ = & { _503_, _013_, _341_ };
  assign _436_ = & { _503_, _013_, _005_ };
  assign _437_ = & { _503_, _013_, _006_ };
  assign _438_ = & { _503_, _013_, _007_ };
  assign _439_ = & { _503_, _013_, _504_ };
  assign _440_ = & { _503_, _013_, _505_ };
  assign _441_ = & { _503_, _013_, _506_ };
  assign _442_ = & { _503_, _013_, _507_ };
  assign _443_ = & { _503_, _013_, _508_ };
  assign _444_ = & { _503_, _013_, _509_ };
  assign _445_ = & { _503_, _013_, _510_ };
  assign _446_ = & { _503_, _013_, _511_ };
  assign _447_ = & { _503_, _013_, _512_ };
  assign _448_ = & { _503_, _013_, _513_ };
  assign _449_ = & { _503_, _013_, _514_ };
  assign _450_ = & { _503_, _013_, _515_ };
  assign _451_ = & { _503_, _013_, _516_ };
  assign _452_ = & { _503_, _013_, _517_ };
  assign _453_ = & { _503_, _013_, _518_ };
  assign _454_ = & { _503_, _013_, _519_ };
  assign _455_ = & { _503_, _013_, _520_ };
  assign _456_ = & { _503_, _013_, _521_ };
  assign _457_ = & { _503_, _013_, _522_ };
  assign _458_ = & { _503_, _013_, _523_ };
  assign _459_ = & { _503_, _013_, _524_ };
  assign _460_ = & { _503_, _013_, _525_ };
  assign _461_ = & { _503_, _013_, _526_ };
  assign _462_ = & { _503_, _013_, _527_ };
  assign _463_ = & { _503_, _013_, _528_ };
  assign _464_ = & { _503_, _013_, _529_ };
  assign _465_ = & { _530_, _503_, _013_ };
  assign _466_ = & { _531_, _503_, _013_ };
  assign _467_ = & { _532_, _503_, _013_ };
  assign _468_ = & { _533_, _503_, _013_ };
  assign _469_ = & { _534_, _503_, _013_ };
  assign _470_ = & { _535_, _503_, _013_ };
  assign _471_ = | { _170_, _169_, _168_ };
  assign _472_ = | { _176_, _175_, _174_ };
  assign _473_ = | { _182_, _181_, _180_ };
  assign _474_ = | { _188_, _187_, _186_ };
  assign _475_ = | { _194_, _193_, _191_ };
  assign _476_ = | { _199_, _198_, _197_ };
  assign _477_ = | { _204_, _203_, _202_ };
  assign _478_ = | { _209_, _208_, _207_ };
  assign _479_ = | { _215_, _214_, _213_ };
  assign _480_ = | { _222_, _221_, _219_ };
  assign _481_ = | { _228_, _227_, _226_ };
  assign _482_ = | { _233_, _232_, _231_ };
  assign _483_ = | { _239_, _238_, _237_ };
  assign _484_ = | { _244_, _243_, _242_ };
  assign _485_ = | { _249_, _248_, _247_ };
  assign _486_ = | { _255_, _254_, _253_ };
  assign _487_ = | { _261_, _260_, _259_ };
  assign _488_ = | { _267_, _266_, _265_ };
  assign _489_ = | { _273_, _272_, _271_ };
  assign _490_ = | { _279_, _278_, _276_ };
  assign _491_ = | { _284_, _283_, _282_ };
  assign _492_ = | { _289_, _288_, _287_ };
  assign _493_ = | { _294_, _293_, _292_ };
  assign _494_ = | { _301_, _300_, _299_ };
  assign _495_ = | { _308_, _307_, _305_ };
  assign _496_ = | { _314_, _313_, _312_ };
  assign _497_ = | { _319_, _318_, _317_ };
  assign _498_ = | { _325_, _324_, _323_ };
  assign _499_ = | { _330_, _329_, _328_ };
  assign _500_ = | { _335_, _334_, _333_ };
  assign _501_ = | { _341_, _340_, _339_ };
  assign _502_ = | { _007_, _006_, _005_ };
  assign tail_bits = head + count[6:0];
  assign _019_ = head[6:5] == 2'h3;
  assign _127_ = _126_ ? _021_ : head[6:5];
  assign _129_ = ! _127_;
  assign _130_ = _127_ == 1'h1;
  assign _131_ = _127_ == 2'h2;
  function [8:0] \1022 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \1022  = b[8:0];
      3'b?1?:
        \1022  = b[17:9];
      3'b1??:
        \1022  = b[26:18];
      default:
        \1022  = a;
    endcase
  endfunction
  assign rd0[17:9] = \1022 (banks[71:63], banks[62:36], { _131_, _130_, _129_ });
  assign _132_ = 5'h1f < head[4:0];
  assign _020_ = head[6:5] + 1'h1;
  assign _133_ = _132_ ? _021_ : head[6:5];
  assign _134_ = ! _133_;
  assign _136_ = _133_ == 1'h1;
  assign _137_ = _133_ == 2'h2;
  function [8:0] \1054 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \1054  = b[8:0];
      3'b?1?:
        \1054  = b[17:9];
      3'b1??:
        \1054  = b[26:18];
      default:
        \1054  = a;
    endcase
  endfunction
  assign rd0[8:0] = \1054 (banks[35:27], banks[26:0], { _137_, _136_, _134_ });
  assign rd1[287:279] = head[0] ? rd0[278:270] : rd0[287:279];
  assign rd1[278:270] = head[0] ? rd0[269:261] : rd0[278:270];
  assign rd1[269:261] = head[0] ? rd0[260:252] : rd0[269:261];
  assign _121_ = _099_ ? _021_ : head[6:5];
  assign rd1[260:252] = head[0] ? rd0[251:243] : rd0[260:252];
  assign rd1[251:243] = head[0] ? rd0[242:234] : rd0[251:243];
  assign rd1[242:234] = head[0] ? rd0[233:225] : rd0[242:234];
  assign rd1[233:225] = head[0] ? rd0[224:216] : rd0[233:225];
  assign rd1[224:216] = head[0] ? rd0[215:207] : rd0[224:216];
  assign rd1[215:207] = head[0] ? rd0[206:198] : rd0[215:207];
  assign rd1[206:198] = head[0] ? rd0[197:189] : rd0[206:198];
  assign rd1[197:189] = head[0] ? rd0[188:180] : rd0[197:189];
  assign rd1[188:180] = head[0] ? rd0[179:171] : rd0[188:180];
  assign rd1[179:171] = head[0] ? rd0[170:162] : rd0[179:171];
  assign rd1[170:162] = head[0] ? rd0[161:153] : rd0[170:162];
  assign rd1[161:153] = head[0] ? rd0[152:144] : rd0[161:153];
  assign rd1[152:144] = head[0] ? rd0[143:135] : rd0[152:144];
  assign rd1[143:135] = head[0] ? rd0[134:126] : rd0[143:135];
  assign rd1[134:126] = head[0] ? rd0[125:117] : rd0[134:126];
  assign rd1[125:117] = head[0] ? rd0[116:108] : rd0[125:117];
  assign rd1[116:108] = head[0] ? rd0[107:99] : rd0[116:108];
  assign rd1[107:99] = head[0] ? rd0[98:90] : rd0[107:99];
  assign rd1[98:90] = head[0] ? rd0[89:81] : rd0[98:90];
  assign rd1[89:81] = head[0] ? rd0[80:72] : rd0[89:81];
  assign rd1[80:72] = head[0] ? rd0[71:63] : rd0[80:72];
  assign rd1[71:63] = head[0] ? rd0[62:54] : rd0[71:63];
  assign rd1[62:54] = head[0] ? rd0[53:45] : rd0[62:54];
  assign rd1[53:45] = head[0] ? rd0[44:36] : rd0[53:45];
  assign rd1[44:36] = head[0] ? rd0[35:27] : rd0[44:36];
  assign _128_ = ! _121_;
  assign rd1[35:27] = head[0] ? rd0[26:18] : rd0[35:27];
  assign rd1[26:18] = head[0] ? rd0[17:9] : rd0[26:18];
  assign rd1[17:9] = head[0] ? rd0[8:0] : rd0[17:9];
  assign rd1[8:0] = head[0] ? rd0[287:279] : rd0[8:0];
  assign rd2[287:279] = head[1] ? rd1[269:261] : rd1[287:279];
  assign rd2[278:270] = head[1] ? rd1[260:252] : rd1[278:270];
  assign rd2[269:261] = head[1] ? rd1[251:243] : rd1[269:261];
  assign rd2[260:252] = head[1] ? rd1[242:234] : rd1[260:252];
  assign _135_ = _121_ == 1'h1;
  assign rd2[251:243] = head[1] ? rd1[233:225] : rd1[251:243];
  assign rd2[242:234] = head[1] ? rd1[224:216] : rd1[242:234];
  assign rd2[233:225] = head[1] ? rd1[215:207] : rd1[233:225];
  assign rd2[224:216] = head[1] ? rd1[206:198] : rd1[224:216];
  assign rd2[215:207] = head[1] ? rd1[197:189] : rd1[215:207];
  assign rd2[206:198] = head[1] ? rd1[188:180] : rd1[206:198];
  assign rd2[197:189] = head[1] ? rd1[179:171] : rd1[197:189];
  assign _138_ = _121_ == 2'h2;
  assign rd2[188:180] = head[1] ? rd1[170:162] : rd1[188:180];
  assign rd2[179:171] = head[1] ? rd1[161:153] : rd1[179:171];
  assign rd2[170:162] = head[1] ? rd1[152:144] : rd1[170:162];
  assign rd2[161:153] = head[1] ? rd1[143:135] : rd1[161:153];
  assign rd2[152:144] = head[1] ? rd1[134:126] : rd1[152:144];
  assign rd2[143:135] = head[1] ? rd1[125:117] : rd1[143:135];
  assign rd2[134:126] = head[1] ? rd1[116:108] : rd1[134:126];
  assign rd2[125:117] = head[1] ? rd1[107:99] : rd1[125:117];
  function [8:0] \126 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \126  = b[8:0];
      3'b?1?:
        \126  = b[17:9];
      3'b1??:
        \126  = b[26:18];
      default:
        \126  = a;
    endcase
  endfunction
  assign rd0[269:261] = \126 (banks[1079:1071], banks[1070:1044], { _138_, _135_, _128_ });
  assign rd2[116:108] = head[1] ? rd1[98:90] : rd1[116:108];
  assign rd2[107:99] = head[1] ? rd1[89:81] : rd1[107:99];
  assign rd2[98:90] = head[1] ? rd1[80:72] : rd1[98:90];
  assign rd2[89:81] = head[1] ? rd1[71:63] : rd1[89:81];
  assign rd2[80:72] = head[1] ? rd1[62:54] : rd1[80:72];
  assign rd2[71:63] = head[1] ? rd1[53:45] : rd1[71:63];
  assign rd2[62:54] = head[1] ? rd1[44:36] : rd1[62:54];
  assign _139_ = 2'h3 < head[4:0];
  assign rd2[53:45] = head[1] ? rd1[35:27] : rd1[53:45];
  assign rd2[44:36] = head[1] ? rd1[26:18] : rd1[44:36];
  assign rd2[35:27] = head[1] ? rd1[17:9] : rd1[35:27];
  assign rd2[26:18] = head[1] ? rd1[8:0] : rd1[26:18];
  assign rd2[17:9] = head[1] ? rd1[287:279] : rd1[17:9];
  assign rd2[8:0] = head[1] ? rd1[278:270] : rd1[8:0];
  assign rd3[287:279] = head[2] ? rd2[251:243] : rd2[287:279];
  assign rd3[278:270] = head[2] ? rd2[242:234] : rd2[278:270];
  assign rd3[269:261] = head[2] ? rd2[233:225] : rd2[269:261];
  assign rd3[260:252] = head[2] ? rd2[224:216] : rd2[260:252];
  assign rd3[251:243] = head[2] ? rd2[215:207] : rd2[251:243];
  assign rd3[242:234] = head[2] ? rd2[206:198] : rd2[242:234];
  assign rd3[233:225] = head[2] ? rd2[197:189] : rd2[233:225];
  assign rd3[224:216] = head[2] ? rd2[188:180] : rd2[224:216];
  assign rd3[215:207] = head[2] ? rd2[179:171] : rd2[215:207];
  assign rd3[206:198] = head[2] ? rd2[170:162] : rd2[206:198];
  assign rd3[197:189] = head[2] ? rd2[161:153] : rd2[197:189];
  assign rd3[188:180] = head[2] ? rd2[152:144] : rd2[188:180];
  assign rd3[179:171] = head[2] ? rd2[143:135] : rd2[179:171];
  assign rd3[170:162] = head[2] ? rd2[134:126] : rd2[170:162];
  assign rd3[161:153] = head[2] ? rd2[125:117] : rd2[161:153];
  assign rd3[152:144] = head[2] ? rd2[116:108] : rd2[152:144];
  assign rd3[143:135] = head[2] ? rd2[107:99] : rd2[143:135];
  assign rd3[134:126] = head[2] ? rd2[98:90] : rd2[134:126];
  assign rd3[125:117] = head[2] ? rd2[89:81] : rd2[125:117];
  assign _140_ = _139_ ? _021_ : head[6:5];
  assign rd3[116:108] = head[2] ? rd2[80:72] : rd2[116:108];
  assign rd3[107:99] = head[2] ? rd2[71:63] : rd2[107:99];
  assign rd3[98:90] = head[2] ? rd2[62:54] : rd2[98:90];
  assign rd3[89:81] = head[2] ? rd2[53:45] : rd2[89:81];
  assign rd3[80:72] = head[2] ? rd2[44:36] : rd2[80:72];
  assign rd3[71:63] = head[2] ? rd2[35:27] : rd2[71:63];
  assign rd3[62:54] = head[2] ? rd2[26:18] : rd2[62:54];
  assign rd3[53:45] = head[2] ? rd2[17:9] : rd2[53:45];
  assign rd3[44:36] = head[2] ? rd2[8:0] : rd2[44:36];
  assign rd3[35:27] = head[2] ? rd2[287:279] : rd2[35:27];
  assign rd3[26:18] = head[2] ? rd2[278:270] : rd2[26:18];
  assign rd3[17:9] = head[2] ? rd2[269:261] : rd2[17:9];
  assign rd3[8:0] = head[2] ? rd2[260:252] : rd2[8:0];
  assign rd4[287:279] = head[3] ? rd3[215:207] : rd3[287:279];
  assign rd4[278:270] = head[3] ? rd3[206:198] : rd3[278:270];
  assign rd4[269:261] = head[3] ? rd3[197:189] : rd3[269:261];
  assign rd4[260:252] = head[3] ? rd3[188:180] : rd3[260:252];
  assign rd4[251:243] = head[3] ? rd3[179:171] : rd3[251:243];
  assign rd4[242:234] = head[3] ? rd3[170:162] : rd3[242:234];
  assign rd4[233:225] = head[3] ? rd3[161:153] : rd3[233:225];
  assign rd4[224:216] = head[3] ? rd3[152:144] : rd3[224:216];
  assign rd4[215:207] = head[3] ? rd3[143:135] : rd3[215:207];
  assign rd4[206:198] = head[3] ? rd3[134:126] : rd3[206:198];
  assign rd4[197:189] = head[3] ? rd3[125:117] : rd3[197:189];
  assign rd4[188:180] = head[3] ? rd3[116:108] : rd3[188:180];
  assign _141_ = ! _140_;
  assign rd4[179:171] = head[3] ? rd3[107:99] : rd3[179:171];
  assign rd4[170:162] = head[3] ? rd3[98:90] : rd3[170:162];
  assign rd4[161:153] = head[3] ? rd3[89:81] : rd3[161:153];
  assign rd4[152:144] = head[3] ? rd3[80:72] : rd3[152:144];
  assign rd4[143:135] = head[3] ? rd3[71:63] : rd3[143:135];
  assign rd4[134:126] = head[3] ? rd3[62:54] : rd3[134:126];
  assign rd4[125:117] = head[3] ? rd3[53:45] : rd3[125:117];
  assign rd4[116:108] = head[3] ? rd3[44:36] : rd3[116:108];
  assign _142_ = _140_ == 1'h1;
  assign rd4[107:99] = head[3] ? rd3[35:27] : rd3[107:99];
  assign rd4[98:90] = head[3] ? rd3[26:18] : rd3[98:90];
  assign rd4[89:81] = head[3] ? rd3[17:9] : rd3[89:81];
  assign rd4[80:72] = head[3] ? rd3[8:0] : rd3[80:72];
  assign rd4[71:63] = head[3] ? rd3[287:279] : rd3[71:63];
  assign rd4[62:54] = head[3] ? rd3[278:270] : rd3[62:54];
  assign rd4[53:45] = head[3] ? rd3[269:261] : rd3[53:45];
  assign _143_ = _140_ == 2'h2;
  assign rd4[44:36] = head[3] ? rd3[260:252] : rd3[44:36];
  assign rd4[35:27] = head[3] ? rd3[251:243] : rd3[35:27];
  assign rd4[26:18] = head[3] ? rd3[242:234] : rd3[26:18];
  assign rd4[17:9] = head[3] ? rd3[233:225] : rd3[17:9];
  assign rd4[8:0] = head[3] ? rd3[224:216] : rd3[8:0];
  assign { WINDOW_FAULT_o[31], WINDOW_o[255:248] } = head[4] ? rd4[143:135] : rd4[287:279];
  assign { WINDOW_FAULT_o[30], WINDOW_o[247:240] } = head[4] ? rd4[134:126] : rd4[278:270];
  assign { WINDOW_FAULT_o[29], WINDOW_o[239:232] } = head[4] ? rd4[125:117] : rd4[269:261];
  function [8:0] \158 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \158  = b[8:0];
      3'b?1?:
        \158  = b[17:9];
      3'b1??:
        \158  = b[26:18];
      default:
        \158  = a;
    endcase
  endfunction
  assign rd0[260:252] = \158 (banks[1043:1035], banks[1034:1008], { _143_, _142_, _141_ });
  assign { WINDOW_FAULT_o[28], WINDOW_o[231:224] } = head[4] ? rd4[116:108] : rd4[260:252];
  assign { WINDOW_FAULT_o[27], WINDOW_o[223:216] } = head[4] ? rd4[107:99] : rd4[251:243];
  assign { WINDOW_FAULT_o[26], WINDOW_o[215:208] } = head[4] ? rd4[98:90] : rd4[242:234];
  assign { WINDOW_FAULT_o[25], WINDOW_o[207:200] } = head[4] ? rd4[89:81] : rd4[233:225];
  assign { WINDOW_FAULT_o[24], WINDOW_o[199:192] } = head[4] ? rd4[80:72] : rd4[224:216];
  assign { WINDOW_FAULT_o[23], WINDOW_o[191:184] } = head[4] ? rd4[71:63] : rd4[215:207];
  assign { WINDOW_FAULT_o[22], WINDOW_o[183:176] } = head[4] ? rd4[62:54] : rd4[206:198];
  assign _144_ = 3'h4 < head[4:0];
  assign { WINDOW_FAULT_o[21], WINDOW_o[175:168] } = head[4] ? rd4[53:45] : rd4[197:189];
  assign { WINDOW_FAULT_o[20], WINDOW_o[167:160] } = head[4] ? rd4[44:36] : rd4[188:180];
  assign { WINDOW_FAULT_o[19], WINDOW_o[159:152] } = head[4] ? rd4[35:27] : rd4[179:171];
  assign { WINDOW_FAULT_o[18], WINDOW_o[151:144] } = head[4] ? rd4[26:18] : rd4[170:162];
  assign { WINDOW_FAULT_o[17], WINDOW_o[143:136] } = head[4] ? rd4[17:9] : rd4[161:153];
  assign { WINDOW_FAULT_o[16], WINDOW_o[135:128] } = head[4] ? rd4[8:0] : rd4[152:144];
  assign { WINDOW_FAULT_o[15], WINDOW_o[127:120] } = head[4] ? rd4[287:279] : rd4[143:135];
  assign { WINDOW_FAULT_o[14], WINDOW_o[119:112] } = head[4] ? rd4[278:270] : rd4[134:126];
  assign { WINDOW_FAULT_o[13], WINDOW_o[111:104] } = head[4] ? rd4[269:261] : rd4[125:117];
  assign { WINDOW_FAULT_o[12], WINDOW_o[103:96] } = head[4] ? rd4[260:252] : rd4[116:108];
  assign { WINDOW_FAULT_o[11], WINDOW_o[95:88] } = head[4] ? rd4[251:243] : rd4[107:99];
  assign { WINDOW_FAULT_o[10], WINDOW_o[87:80] } = head[4] ? rd4[242:234] : rd4[98:90];
  assign { WINDOW_FAULT_o[9], WINDOW_o[79:72] } = head[4] ? rd4[233:225] : rd4[89:81];
  assign { WINDOW_FAULT_o[8], WINDOW_o[71:64] } = head[4] ? rd4[224:216] : rd4[80:72];
  assign { WINDOW_FAULT_o[7], WINDOW_o[63:56] } = head[4] ? rd4[215:207] : rd4[71:63];
  assign { WINDOW_FAULT_o[6], WINDOW_o[55:48] } = head[4] ? rd4[206:198] : rd4[62:54];
  assign { WINDOW_FAULT_o[5], WINDOW_o[47:40] } = head[4] ? rd4[197:189] : rd4[53:45];
  assign { WINDOW_FAULT_o[4], WINDOW_o[39:32] } = head[4] ? rd4[188:180] : rd4[44:36];
  assign { WINDOW_FAULT_o[3], WINDOW_o[31:24] } = head[4] ? rd4[179:171] : rd4[35:27];
  assign { WINDOW_FAULT_o[2], WINDOW_o[23:16] } = head[4] ? rd4[170:162] : rd4[26:18];
  assign { WINDOW_FAULT_o[1], WINDOW_o[15:8] } = head[4] ? rd4[161:153] : rd4[17:9];
  assign { WINDOW_FAULT_o[0], WINDOW_o[7:0] } = head[4] ? rd4[152:144] : rd4[8:0];
  assign _079_ = count <= 7'h60;
  assign _021_ = _019_ ? 2'h0 : _020_;
  assign _145_ = _144_ ? _021_ : head[6:5];
  assign _146_ = count > 6'h20;
  assign WINDOW_COUNT_o = _146_ ? 6'h20 : count[5:0];
  assign _147_ = ! count;
  assign EMPTY_o = _147_ ? 1'h1 : 1'h0;
  assign ready = _079_ ? 1'h1 : 1'h0;
  assign _148_ = ! _145_;
  assign _149_ = _145_ == 1'h1;
  assign _150_ = _145_ == 2'h2;
  function [8:0] \190 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \190  = b[8:0];
      3'b?1?:
        \190  = b[17:9];
      3'b1??:
        \190  = b[26:18];
      default:
        \190  = a;
    endcase
  endfunction
  assign rd0[251:243] = \190 (banks[1007:999], banks[998:972], { _150_, _149_, _148_ });
  assign _152_ = 3'h5 < head[4:0];
  assign _153_ = _152_ ? _021_ : head[6:5];
  assign wr1[286:279] = tail_bits[0] ? FETCH_BLOCK_i[7:0] : FETCH_BLOCK_i[255:248];
  assign wr1[277:270] = tail_bits[0] ? FETCH_BLOCK_i[255:248] : FETCH_BLOCK_i[247:240];
  assign wr1[268:261] = tail_bits[0] ? FETCH_BLOCK_i[247:240] : FETCH_BLOCK_i[239:232];
  assign wr1[259:252] = tail_bits[0] ? FETCH_BLOCK_i[239:232] : FETCH_BLOCK_i[231:224];
  assign wr1[250:243] = tail_bits[0] ? FETCH_BLOCK_i[231:224] : FETCH_BLOCK_i[223:216];
  assign wr1[241:234] = tail_bits[0] ? FETCH_BLOCK_i[223:216] : FETCH_BLOCK_i[215:208];
  assign wr1[232:225] = tail_bits[0] ? FETCH_BLOCK_i[215:208] : FETCH_BLOCK_i[207:200];
  assign wr1[223:216] = tail_bits[0] ? FETCH_BLOCK_i[207:200] : FETCH_BLOCK_i[199:192];
  assign _154_ = ! _153_;
  assign wr1[214:207] = tail_bits[0] ? FETCH_BLOCK_i[199:192] : FETCH_BLOCK_i[191:184];
  assign wr1[205:198] = tail_bits[0] ? FETCH_BLOCK_i[191:184] : FETCH_BLOCK_i[183:176];
  assign wr1[196:189] = tail_bits[0] ? FETCH_BLOCK_i[183:176] : FETCH_BLOCK_i[175:168];
  assign wr1[187:180] = tail_bits[0] ? FETCH_BLOCK_i[175:168] : FETCH_BLOCK_i[167:160];
  assign wr1[178:171] = tail_bits[0] ? FETCH_BLOCK_i[167:160] : FETCH_BLOCK_i[159:152];
  assign wr1[169:162] = tail_bits[0] ? FETCH_BLOCK_i[159:152] : FETCH_BLOCK_i[151:144];
  assign wr1[160:153] = tail_bits[0] ? FETCH_BLOCK_i[151:144] : FETCH_BLOCK_i[143:136];
  assign wr1[151:144] = tail_bits[0] ? FETCH_BLOCK_i[143:136] : FETCH_BLOCK_i[135:128];
  assign _155_ = _153_ == 1'h1;
  assign wr1[142:135] = tail_bits[0] ? FETCH_BLOCK_i[135:128] : FETCH_BLOCK_i[127:120];
  assign wr1[133:126] = tail_bits[0] ? FETCH_BLOCK_i[127:120] : FETCH_BLOCK_i[119:112];
  assign wr1[124:117] = tail_bits[0] ? FETCH_BLOCK_i[119:112] : FETCH_BLOCK_i[111:104];
  assign wr1[115:108] = tail_bits[0] ? FETCH_BLOCK_i[111:104] : FETCH_BLOCK_i[103:96];
  assign wr1[106:99] = tail_bits[0] ? FETCH_BLOCK_i[103:96] : FETCH_BLOCK_i[95:88];
  assign wr1[97:90] = tail_bits[0] ? FETCH_BLOCK_i[95:88] : FETCH_BLOCK_i[87:80];
  assign wr1[88:81] = tail_bits[0] ? FETCH_BLOCK_i[87:80] : FETCH_BLOCK_i[79:72];
  assign _156_ = _153_ == 2'h2;
  assign wr1[79:72] = tail_bits[0] ? FETCH_BLOCK_i[79:72] : FETCH_BLOCK_i[71:64];
  assign wr1[70:63] = tail_bits[0] ? FETCH_BLOCK_i[71:64] : FETCH_BLOCK_i[63:56];
  assign wr1[61:54] = tail_bits[0] ? FETCH_BLOCK_i[63:56] : FETCH_BLOCK_i[55:48];
  assign wr1[52:45] = tail_bits[0] ? FETCH_BLOCK_i[55:48] : FETCH_BLOCK_i[47:40];
  assign wr1[43:36] = tail_bits[0] ? FETCH_BLOCK_i[47:40] : FETCH_BLOCK_i[39:32];
  assign wr1[34:27] = tail_bits[0] ? FETCH_BLOCK_i[39:32] : FETCH_BLOCK_i[31:24];
  assign wr1[25:18] = tail_bits[0] ? FETCH_BLOCK_i[31:24] : FETCH_BLOCK_i[23:16];
  assign wr1[16:9] = tail_bits[0] ? FETCH_BLOCK_i[23:16] : FETCH_BLOCK_i[15:8];
  function [8:0] \222 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \222  = b[8:0];
      3'b?1?:
        \222  = b[17:9];
      3'b1??:
        \222  = b[26:18];
      default:
        \222  = a;
    endcase
  endfunction
  assign rd0[242:234] = \222 (banks[971:963], banks[962:936], { _156_, _155_, _154_ });
  assign wr1[7:0] = tail_bits[0] ? FETCH_BLOCK_i[15:8] : FETCH_BLOCK_i[7:0];
  assign wr2[286:279] = tail_bits[1] ? wr1[16:9] : wr1[286:279];
  assign wr2[277:270] = tail_bits[1] ? wr1[7:0] : wr1[277:270];
  assign wr2[268:261] = tail_bits[1] ? wr1[286:279] : wr1[268:261];
  assign wr2[259:252] = tail_bits[1] ? wr1[277:270] : wr1[259:252];
  assign wr2[250:243] = tail_bits[1] ? wr1[268:261] : wr1[250:243];
  assign wr2[241:234] = tail_bits[1] ? wr1[259:252] : wr1[241:234];
  assign _157_ = 3'h6 < head[4:0];
  assign wr2[232:225] = tail_bits[1] ? wr1[250:243] : wr1[232:225];
  assign wr2[223:216] = tail_bits[1] ? wr1[241:234] : wr1[223:216];
  assign wr2[214:207] = tail_bits[1] ? wr1[232:225] : wr1[214:207];
  assign wr2[205:198] = tail_bits[1] ? wr1[223:216] : wr1[205:198];
  assign wr2[196:189] = tail_bits[1] ? wr1[214:207] : wr1[196:189];
  assign wr2[187:180] = tail_bits[1] ? wr1[205:198] : wr1[187:180];
  assign wr2[178:171] = tail_bits[1] ? wr1[196:189] : wr1[178:171];
  assign wr2[169:162] = tail_bits[1] ? wr1[187:180] : wr1[169:162];
  assign wr2[160:153] = tail_bits[1] ? wr1[178:171] : wr1[160:153];
  assign wr2[151:144] = tail_bits[1] ? wr1[169:162] : wr1[151:144];
  assign wr2[142:135] = tail_bits[1] ? wr1[160:153] : wr1[142:135];
  assign wr2[133:126] = tail_bits[1] ? wr1[151:144] : wr1[133:126];
  assign wr2[124:117] = tail_bits[1] ? wr1[142:135] : wr1[124:117];
  assign wr2[115:108] = tail_bits[1] ? wr1[133:126] : wr1[115:108];
  assign wr2[106:99] = tail_bits[1] ? wr1[124:117] : wr1[106:99];
  assign wr2[97:90] = tail_bits[1] ? wr1[115:108] : wr1[97:90];
  assign wr2[88:81] = tail_bits[1] ? wr1[106:99] : wr1[88:81];
  assign wr2[79:72] = tail_bits[1] ? wr1[97:90] : wr1[79:72];
  assign wr2[70:63] = tail_bits[1] ? wr1[88:81] : wr1[70:63];
  assign wr2[61:54] = tail_bits[1] ? wr1[79:72] : wr1[61:54];
  assign wr2[52:45] = tail_bits[1] ? wr1[70:63] : wr1[52:45];
  assign wr2[43:36] = tail_bits[1] ? wr1[61:54] : wr1[43:36];
  assign wr2[34:27] = tail_bits[1] ? wr1[52:45] : wr1[34:27];
  assign wr2[25:18] = tail_bits[1] ? wr1[43:36] : wr1[25:18];
  assign wr2[16:9] = tail_bits[1] ? wr1[34:27] : wr1[16:9];
  assign _166_ = _157_ ? _021_ : head[6:5];
  assign wr2[7:0] = tail_bits[1] ? wr1[25:18] : wr1[7:0];
  assign wr3[286:279] = tail_bits[2] ? wr2[34:27] : wr2[286:279];
  assign wr3[277:270] = tail_bits[2] ? wr2[25:18] : wr2[277:270];
  assign wr3[268:261] = tail_bits[2] ? wr2[16:9] : wr2[268:261];
  assign wr3[259:252] = tail_bits[2] ? wr2[7:0] : wr2[259:252];
  assign wr3[250:243] = tail_bits[2] ? wr2[286:279] : wr2[250:243];
  assign wr3[241:234] = tail_bits[2] ? wr2[277:270] : wr2[241:234];
  assign wr3[232:225] = tail_bits[2] ? wr2[268:261] : wr2[232:225];
  assign wr3[223:216] = tail_bits[2] ? wr2[259:252] : wr2[223:216];
  assign wr3[214:207] = tail_bits[2] ? wr2[250:243] : wr2[214:207];
  assign wr3[205:198] = tail_bits[2] ? wr2[241:234] : wr2[205:198];
  assign wr3[196:189] = tail_bits[2] ? wr2[232:225] : wr2[196:189];
  assign wr3[187:180] = tail_bits[2] ? wr2[223:216] : wr2[187:180];
  assign wr3[178:171] = tail_bits[2] ? wr2[214:207] : wr2[178:171];
  assign wr3[169:162] = tail_bits[2] ? wr2[205:198] : wr2[169:162];
  assign wr3[160:153] = tail_bits[2] ? wr2[196:189] : wr2[160:153];
  assign wr3[151:144] = tail_bits[2] ? wr2[187:180] : wr2[151:144];
  assign wr3[142:135] = tail_bits[2] ? wr2[178:171] : wr2[142:135];
  assign wr3[133:126] = tail_bits[2] ? wr2[169:162] : wr2[133:126];
  assign wr3[124:117] = tail_bits[2] ? wr2[160:153] : wr2[124:117];
  assign wr3[115:108] = tail_bits[2] ? wr2[151:144] : wr2[115:108];
  assign wr3[106:99] = tail_bits[2] ? wr2[142:135] : wr2[106:99];
  assign wr3[97:90] = tail_bits[2] ? wr2[133:126] : wr2[97:90];
  assign wr3[88:81] = tail_bits[2] ? wr2[124:117] : wr2[88:81];
  assign wr3[79:72] = tail_bits[2] ? wr2[115:108] : wr2[79:72];
  assign _172_ = ! _166_;
  assign wr3[70:63] = tail_bits[2] ? wr2[106:99] : wr2[70:63];
  assign wr3[61:54] = tail_bits[2] ? wr2[97:90] : wr2[61:54];
  assign wr3[52:45] = tail_bits[2] ? wr2[88:81] : wr2[52:45];
  assign wr3[43:36] = tail_bits[2] ? wr2[79:72] : wr2[43:36];
  assign wr3[34:27] = tail_bits[2] ? wr2[70:63] : wr2[34:27];
  assign wr3[25:18] = tail_bits[2] ? wr2[61:54] : wr2[25:18];
  assign wr3[16:9] = tail_bits[2] ? wr2[52:45] : wr2[16:9];
  assign wr3[7:0] = tail_bits[2] ? wr2[43:36] : wr2[7:0];
  assign _177_ = _166_ == 1'h1;
  assign wr4[286:279] = tail_bits[3] ? wr3[70:63] : wr3[286:279];
  assign wr4[277:270] = tail_bits[3] ? wr3[61:54] : wr3[277:270];
  assign wr4[268:261] = tail_bits[3] ? wr3[52:45] : wr3[268:261];
  assign wr4[259:252] = tail_bits[3] ? wr3[43:36] : wr3[259:252];
  assign wr4[250:243] = tail_bits[3] ? wr3[34:27] : wr3[250:243];
  assign wr4[241:234] = tail_bits[3] ? wr3[25:18] : wr3[241:234];
  assign wr4[232:225] = tail_bits[3] ? wr3[16:9] : wr3[232:225];
  assign _183_ = _166_ == 2'h2;
  assign wr4[223:216] = tail_bits[3] ? wr3[7:0] : wr3[223:216];
  assign wr4[214:207] = tail_bits[3] ? wr3[286:279] : wr3[214:207];
  assign wr4[205:198] = tail_bits[3] ? wr3[277:270] : wr3[205:198];
  assign wr4[196:189] = tail_bits[3] ? wr3[268:261] : wr3[196:189];
  assign wr4[187:180] = tail_bits[3] ? wr3[259:252] : wr3[187:180];
  assign wr4[178:171] = tail_bits[3] ? wr3[250:243] : wr3[178:171];
  assign wr4[169:162] = tail_bits[3] ? wr3[241:234] : wr3[169:162];
  assign wr4[160:153] = tail_bits[3] ? wr3[232:225] : wr3[160:153];
  function [8:0] \254 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \254  = b[8:0];
      3'b?1?:
        \254  = b[17:9];
      3'b1??:
        \254  = b[26:18];
      default:
        \254  = a;
    endcase
  endfunction
  assign rd0[233:225] = \254 (banks[935:927], banks[926:900], { _183_, _177_, _172_ });
  assign wr4[151:144] = tail_bits[3] ? wr3[223:216] : wr3[151:144];
  assign wr4[142:135] = tail_bits[3] ? wr3[214:207] : wr3[142:135];
  assign wr4[133:126] = tail_bits[3] ? wr3[205:198] : wr3[133:126];
  assign wr4[124:117] = tail_bits[3] ? wr3[196:189] : wr3[124:117];
  assign wr4[115:108] = tail_bits[3] ? wr3[187:180] : wr3[115:108];
  assign wr4[106:99] = tail_bits[3] ? wr3[178:171] : wr3[106:99];
  assign wr4[97:90] = tail_bits[3] ? wr3[169:162] : wr3[97:90];
  assign _192_ = 3'h7 < head[4:0];
  assign wr4[88:81] = tail_bits[3] ? wr3[160:153] : wr3[88:81];
  assign wr4[79:72] = tail_bits[3] ? wr3[151:144] : wr3[79:72];
  assign wr4[70:63] = tail_bits[3] ? wr3[142:135] : wr3[70:63];
  assign wr4[61:54] = tail_bits[3] ? wr3[133:126] : wr3[61:54];
  assign wr4[52:45] = tail_bits[3] ? wr3[124:117] : wr3[52:45];
  assign wr4[43:36] = tail_bits[3] ? wr3[115:108] : wr3[43:36];
  assign wr4[34:27] = tail_bits[3] ? wr3[106:99] : wr3[34:27];
  assign wr4[25:18] = tail_bits[3] ? wr3[97:90] : wr3[25:18];
  assign wr4[16:9] = tail_bits[3] ? wr3[88:81] : wr3[16:9];
  assign wr4[7:0] = tail_bits[3] ? wr3[79:72] : wr3[7:0];
  assign wr5[286:279] = tail_bits[4] ? wr4[142:135] : wr4[286:279];
  assign wr5[277:270] = tail_bits[4] ? wr4[133:126] : wr4[277:270];
  assign wr5[268:261] = tail_bits[4] ? wr4[124:117] : wr4[268:261];
  assign wr5[259:252] = tail_bits[4] ? wr4[115:108] : wr4[259:252];
  assign wr5[250:243] = tail_bits[4] ? wr4[106:99] : wr4[250:243];
  assign wr5[241:234] = tail_bits[4] ? wr4[97:90] : wr4[241:234];
  assign wr5[232:225] = tail_bits[4] ? wr4[88:81] : wr4[232:225];
  assign wr5[223:216] = tail_bits[4] ? wr4[79:72] : wr4[223:216];
  assign wr5[214:207] = tail_bits[4] ? wr4[70:63] : wr4[214:207];
  assign wr5[205:198] = tail_bits[4] ? wr4[61:54] : wr4[205:198];
  assign wr5[196:189] = tail_bits[4] ? wr4[52:45] : wr4[196:189];
  assign wr5[187:180] = tail_bits[4] ? wr4[43:36] : wr4[187:180];
  assign wr5[178:171] = tail_bits[4] ? wr4[34:27] : wr4[178:171];
  assign wr5[169:162] = tail_bits[4] ? wr4[25:18] : wr4[169:162];
  assign wr5[160:153] = tail_bits[4] ? wr4[16:9] : wr4[160:153];
  assign _210_ = _192_ ? _021_ : head[6:5];
  assign wr5[151:144] = tail_bits[4] ? wr4[7:0] : wr4[151:144];
  assign wr5[142:135] = tail_bits[4] ? wr4[286:279] : wr4[142:135];
  assign wr5[133:126] = tail_bits[4] ? wr4[277:270] : wr4[133:126];
  assign wr5[124:117] = tail_bits[4] ? wr4[268:261] : wr4[124:117];
  assign wr5[115:108] = tail_bits[4] ? wr4[259:252] : wr4[115:108];
  assign wr5[106:99] = tail_bits[4] ? wr4[250:243] : wr4[106:99];
  assign wr5[97:90] = tail_bits[4] ? wr4[241:234] : wr4[97:90];
  assign wr5[88:81] = tail_bits[4] ? wr4[232:225] : wr4[88:81];
  assign wr5[79:72] = tail_bits[4] ? wr4[223:216] : wr4[79:72];
  assign wr5[70:63] = tail_bits[4] ? wr4[214:207] : wr4[70:63];
  assign wr5[61:54] = tail_bits[4] ? wr4[205:198] : wr4[61:54];
  assign wr5[52:45] = tail_bits[4] ? wr4[196:189] : wr4[52:45];
  assign wr5[43:36] = tail_bits[4] ? wr4[187:180] : wr4[43:36];
  assign wr5[34:27] = tail_bits[4] ? wr4[178:171] : wr4[34:27];
  assign wr5[25:18] = tail_bits[4] ? wr4[169:162] : wr4[25:18];
  assign wr5[16:9] = tail_bits[4] ? wr4[160:153] : wr4[16:9];
  assign wr5[7:0] = tail_bits[4] ? wr4[151:144] : wr4[7:0];
  assign _158_ = RESET_i | FLUSH_i;
  assign _159_ = CONSUME_i ? CONSUMED_BYTES_i : 6'h00;
  assign _160_ = ready & FETCH_VALID_i;
  assign _161_ = _160_ ? FETCH_COUNT_i : 6'h00;
  assign _162_ = _159_ > count;
  assign _163_ = _162_ ? count[5:0] : _159_;
  assign _216_ = ! _210_;
  assign _013_ = _161_ > 1'h0;
  assign _164_ = 1'h0 < tail_bits[4:0];
  assign _165_ = tail_bits[6:5] == 2'h3;
  assign _002_ = tail_bits[6:5] + 1'h1;
  assign _003_ = _165_ ? 2'h0 : _002_;
  assign _167_ = _164_ ? _003_ : tail_bits[6:5];
  assign _168_ = ! _167_;
  assign _169_ = _167_ == 1'h1;
  assign _170_ = _167_ == 2'h2;
  assign _220_ = _210_ == 1'h1;
  assign _171_ = 1'h1 < tail_bits[4:0];
  assign _173_ = _171_ ? _003_ : tail_bits[6:5];
  assign _174_ = ! _173_;
  assign _175_ = _173_ == 1'h1;
  assign _176_ = _173_ == 2'h2;
  assign _224_ = _210_ == 2'h2;
  assign _178_ = 2'h2 < tail_bits[4:0];
  assign _179_ = _178_ ? _003_ : tail_bits[6:5];
  assign _180_ = ! _179_;
  assign _181_ = _179_ == 1'h1;
  function [8:0] \286 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \286  = b[8:0];
      3'b?1?:
        \286  = b[17:9];
      3'b1??:
        \286  = b[26:18];
      default:
        \286  = a;
    endcase
  endfunction
  assign rd0[224:216] = \286 (banks[899:891], banks[890:864], { _224_, _220_, _216_ });
  assign _182_ = _179_ == 2'h2;
  assign _184_ = 2'h3 < tail_bits[4:0];
  assign _185_ = _184_ ? _003_ : tail_bits[6:5];
  assign _186_ = ! _185_;
  assign _187_ = _185_ == 1'h1;
  assign _234_ = 4'h8 < head[4:0];
  assign _188_ = _185_ == 2'h2;
  assign _189_ = 3'h4 < tail_bits[4:0];
  assign _190_ = _189_ ? _003_ : tail_bits[6:5];
  assign _191_ = ! _190_;
  assign _193_ = _190_ == 1'h1;
  assign _194_ = _190_ == 2'h2;
  assign _195_ = 3'h5 < tail_bits[4:0];
  assign _196_ = _195_ ? _003_ : tail_bits[6:5];
  assign _197_ = ! _196_;
  assign _198_ = _196_ == 1'h1;
  assign _199_ = _196_ == 2'h2;
  assign _200_ = 3'h6 < tail_bits[4:0];
  assign _201_ = _200_ ? _003_ : tail_bits[6:5];
  assign _202_ = ! _201_;
  assign _203_ = _201_ == 1'h1;
  assign _204_ = _201_ == 2'h2;
  assign _251_ = _234_ ? _021_ : head[6:5];
  assign _205_ = 3'h7 < tail_bits[4:0];
  assign _206_ = _205_ ? _003_ : tail_bits[6:5];
  assign _207_ = ! _206_;
  assign _208_ = _206_ == 1'h1;
  assign _209_ = _206_ == 2'h2;
  assign _211_ = 4'h8 < tail_bits[4:0];
  assign _212_ = _211_ ? _003_ : tail_bits[6:5];
  assign _213_ = ! _212_;
  assign _214_ = _212_ == 1'h1;
  assign _215_ = _212_ == 2'h2;
  assign _217_ = 4'h9 < tail_bits[4:0];
  assign _218_ = _217_ ? _003_ : tail_bits[6:5];
  assign _219_ = ! _218_;
  assign _221_ = _218_ == 1'h1;
  assign _222_ = _218_ == 2'h2;
  assign _257_ = ! _251_;
  assign _223_ = 4'ha < tail_bits[4:0];
  assign _225_ = _223_ ? _003_ : tail_bits[6:5];
  assign _226_ = ! _225_;
  assign _227_ = _225_ == 1'h1;
  assign _228_ = _225_ == 2'h2;
  assign _262_ = _251_ == 1'h1;
  assign _229_ = 4'hb < tail_bits[4:0];
  assign _230_ = _229_ ? _003_ : tail_bits[6:5];
  assign _231_ = ! _230_;
  assign _232_ = _230_ == 1'h1;
  assign _233_ = _230_ == 2'h2;
  assign _268_ = _251_ == 2'h2;
  assign _235_ = 4'hc < tail_bits[4:0];
  assign _236_ = _235_ ? _003_ : tail_bits[6:5];
  assign _237_ = ! _236_;
  assign _238_ = _236_ == 1'h1;
  function [8:0] \318 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \318  = b[8:0];
      3'b?1?:
        \318  = b[17:9];
      3'b1??:
        \318  = b[26:18];
      default:
        \318  = a;
    endcase
  endfunction
  assign rd0[215:207] = \318 (banks[863:855], banks[854:828], { _268_, _262_, _257_ });
  assign _239_ = _236_ == 2'h2;
  assign _240_ = 4'hd < tail_bits[4:0];
  assign _241_ = _240_ ? _003_ : tail_bits[6:5];
  assign _242_ = ! _241_;
  assign _243_ = _241_ == 1'h1;
  assign _277_ = 4'h9 < head[4:0];
  assign _244_ = _241_ == 2'h2;
  assign _245_ = 4'he < tail_bits[4:0];
  assign _246_ = _245_ ? _003_ : tail_bits[6:5];
  assign _247_ = ! _246_;
  assign _248_ = _246_ == 1'h1;
  assign _249_ = _246_ == 2'h2;
  assign _250_ = 4'hf < tail_bits[4:0];
  assign _252_ = _250_ ? _003_ : tail_bits[6:5];
  assign _253_ = ! _252_;
  assign _254_ = _252_ == 1'h1;
  assign _255_ = _252_ == 2'h2;
  assign _256_ = 5'h10 < tail_bits[4:0];
  assign _258_ = _256_ ? _003_ : tail_bits[6:5];
  assign _151_ = 1'h0 < head[4:0];
  assign _259_ = ! _258_;
  assign _260_ = _258_ == 1'h1;
  assign _261_ = _258_ == 2'h2;
  assign _296_ = _277_ ? _021_ : head[6:5];
  assign _263_ = 5'h11 < tail_bits[4:0];
  assign _264_ = _263_ ? _003_ : tail_bits[6:5];
  assign _265_ = ! _264_;
  assign _266_ = _264_ == 1'h1;
  assign _267_ = _264_ == 2'h2;
  assign _269_ = 5'h12 < tail_bits[4:0];
  assign _270_ = _269_ ? _003_ : tail_bits[6:5];
  assign _271_ = ! _270_;
  assign _272_ = _270_ == 1'h1;
  assign _273_ = _270_ == 2'h2;
  assign _274_ = 5'h13 < tail_bits[4:0];
  assign _275_ = _274_ ? _003_ : tail_bits[6:5];
  assign _276_ = ! _275_;
  assign _278_ = _275_ == 1'h1;
  assign _279_ = _275_ == 2'h2;
  assign _302_ = ! _296_;
  assign _280_ = 5'h14 < tail_bits[4:0];
  assign _281_ = _280_ ? _003_ : tail_bits[6:5];
  assign _282_ = ! _281_;
  assign _283_ = _281_ == 1'h1;
  assign _284_ = _281_ == 2'h2;
  assign _306_ = _296_ == 1'h1;
  assign _285_ = 5'h15 < tail_bits[4:0];
  assign _286_ = _285_ ? _003_ : tail_bits[6:5];
  assign _287_ = ! _286_;
  assign _288_ = _286_ == 1'h1;
  assign _289_ = _286_ == 2'h2;
  assign _310_ = _296_ == 2'h2;
  assign _290_ = 5'h16 < tail_bits[4:0];
  assign _291_ = _290_ ? _003_ : tail_bits[6:5];
  assign _292_ = ! _291_;
  assign _293_ = _291_ == 1'h1;
  function [8:0] \350 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \350  = b[8:0];
      3'b?1?:
        \350  = b[17:9];
      3'b1??:
        \350  = b[26:18];
      default:
        \350  = a;
    endcase
  endfunction
  assign rd0[206:198] = \350 (banks[827:819], banks[818:792], { _310_, _306_, _302_ });
  assign _294_ = _291_ == 2'h2;
  assign _297_ = 5'h17 < tail_bits[4:0];
  assign _298_ = _297_ ? _003_ : tail_bits[6:5];
  assign _299_ = ! _298_;
  assign _300_ = _298_ == 1'h1;
  assign _320_ = 4'ha < head[4:0];
  assign _301_ = _298_ == 2'h2;
  assign _303_ = 5'h18 < tail_bits[4:0];
  assign _304_ = _303_ ? _003_ : tail_bits[6:5];
  assign _305_ = ! _304_;
  assign _307_ = _304_ == 1'h1;
  assign _308_ = _304_ == 2'h2;
  assign _309_ = 5'h19 < tail_bits[4:0];
  assign _311_ = _309_ ? _003_ : tail_bits[6:5];
  assign _312_ = ! _311_;
  assign _313_ = _311_ == 1'h1;
  assign _314_ = _311_ == 2'h2;
  assign _315_ = 5'h1a < tail_bits[4:0];
  assign _316_ = _315_ ? _003_ : tail_bits[6:5];
  assign _317_ = ! _316_;
  assign _318_ = _316_ == 1'h1;
  assign _319_ = _316_ == 2'h2;
  assign _337_ = _320_ ? _021_ : head[6:5];
  assign _321_ = 5'h1b < tail_bits[4:0];
  assign _322_ = _321_ ? _003_ : tail_bits[6:5];
  assign _323_ = ! _322_;
  assign _324_ = _322_ == 1'h1;
  assign _325_ = _322_ == 2'h2;
  assign _326_ = 5'h1c < tail_bits[4:0];
  assign _327_ = _326_ ? _003_ : tail_bits[6:5];
  assign _328_ = ! _327_;
  assign _329_ = _327_ == 1'h1;
  assign _330_ = _327_ == 2'h2;
  assign _331_ = 5'h1d < tail_bits[4:0];
  assign _332_ = _331_ ? _003_ : tail_bits[6:5];
  assign _333_ = ! _332_;
  assign _334_ = _332_ == 1'h1;
  assign _335_ = _332_ == 2'h2;
  assign _001_ = ! _337_;
  assign _336_ = 5'h1e < tail_bits[4:0];
  assign _338_ = _336_ ? _003_ : tail_bits[6:5];
  assign _339_ = ! _338_;
  assign _340_ = _338_ == 1'h1;
  assign _341_ = _338_ == 2'h2;
  assign _008_ = _337_ == 1'h1;
  assign _342_ = 5'h1f < tail_bits[4:0];
  assign _004_ = _342_ ? _003_ : tail_bits[6:5];
  assign _005_ = ! _004_;
  assign _006_ = _004_ == 1'h1;
  assign _007_ = _004_ == 2'h2;
  assign _017_ = _337_ == 2'h2;
  assign _009_ = count - _163_;
  assign _010_ = head + _163_;
  assign _011_ = _009_ + _161_;
  assign _012_ = ! _009_;
  function [8:0] \382 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \382  = b[8:0];
      3'b?1?:
        \382  = b[17:9];
      3'b1??:
        \382  = b[26:18];
      default:
        \382  = a;
    endcase
  endfunction
  assign rd0[197:189] = \382 (banks[791:783], banks[782:756], { _017_, _008_, _001_ });
  assign _014_ = _013_ & _012_;
  assign _015_ = head_pc + _163_;
  assign _016_ = _014_ ? FETCH_PC_i : _015_;
  assign _018_ = 4'hb < head[4:0];
  assign _022_ = _018_ ? _021_ : head[6:5];
  assign _023_ = ! _022_;
  assign _025_ = _022_ == 1'h1;
  assign _026_ = _022_ == 2'h2;
  function [8:0] \414 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \414  = b[8:0];
      3'b?1?:
        \414  = b[17:9];
      3'b1??:
        \414  = b[26:18];
      default:
        \414  = a;
    endcase
  endfunction
  assign rd0[188:180] = \414 (banks[755:747], banks[746:720], { _026_, _025_, _023_ });
  assign _027_ = 4'hc < head[4:0];
  assign _028_ = _027_ ? _021_ : head[6:5];
  assign _295_ = _151_ ? _021_ : head[6:5];
  assign _029_ = ! _028_;
  assign _030_ = _028_ == 1'h1;
  assign _032_ = _028_ == 2'h2;
  function [8:0] \446 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \446  = b[8:0];
      3'b?1?:
        \446  = b[17:9];
      3'b1??:
        \446  = b[26:18];
      default:
        \446  = a;
    endcase
  endfunction
  assign rd0[179:171] = \446 (banks[719:711], banks[710:684], { _032_, _030_, _029_ });
  assign _033_ = 4'hd < head[4:0];
  assign _034_ = _033_ ? _021_ : head[6:5];
  assign _035_ = ! _034_;
  assign _036_ = _034_ == 1'h1;
  assign _037_ = _034_ == 2'h2;
  function [8:0] \478 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \478  = b[8:0];
      3'b?1?:
        \478  = b[17:9];
      3'b1??:
        \478  = b[26:18];
      default:
        \478  = a;
    endcase
  endfunction
  assign rd0[170:162] = \478 (banks[683:675], banks[674:648], { _037_, _036_, _035_ });
  assign _038_ = 4'he < head[4:0];
  assign _039_ = _038_ ? _021_ : head[6:5];
  assign _040_ = ! _039_;
  assign _041_ = _039_ == 1'h1;
  assign _042_ = _039_ == 2'h2;
  function [8:0] \510 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \510  = b[8:0];
      3'b?1?:
        \510  = b[17:9];
      3'b1??:
        \510  = b[26:18];
      default:
        \510  = a;
    endcase
  endfunction
  assign rd0[161:153] = \510 (banks[647:639], banks[638:612], { _042_, _041_, _040_ });
  assign _044_ = 4'hf < head[4:0];
  assign _045_ = _044_ ? _021_ : head[6:5];
  assign _000_ = ! _295_;
  assign _046_ = ! _045_;
  assign _047_ = _045_ == 1'h1;
  assign _048_ = _045_ == 2'h2;
  function [8:0] \542 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \542  = b[8:0];
      3'b?1?:
        \542  = b[17:9];
      3'b1??:
        \542  = b[26:18];
      default:
        \542  = a;
    endcase
  endfunction
  assign rd0[152:144] = \542 (banks[611:603], banks[602:576], { _048_, _047_, _046_ });
  assign _049_ = 5'h10 < head[4:0];
  assign _050_ = _049_ ? _021_ : head[6:5];
  assign _024_ = _295_ == 1'h1;
  assign _051_ = ! _050_;
  assign _052_ = _050_ == 1'h1;
  assign _053_ = _050_ == 2'h2;
  function [8:0] \574 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \574  = b[8:0];
      3'b?1?:
        \574  = b[17:9];
      3'b1??:
        \574  = b[26:18];
      default:
        \574  = a;
    endcase
  endfunction
  assign rd0[143:135] = \574 (banks[575:567], banks[566:540], { _053_, _052_, _051_ });
  assign _054_ = 5'h11 < head[4:0];
  assign _055_ = _054_ ? _021_ : head[6:5];
  assign _031_ = _295_ == 2'h2;
  assign _056_ = ! _055_;
  assign _057_ = _055_ == 1'h1;
  assign _058_ = _055_ == 2'h2;
  function [8:0] \606 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \606  = b[8:0];
      3'b?1?:
        \606  = b[17:9];
      3'b1??:
        \606  = b[26:18];
      default:
        \606  = a;
    endcase
  endfunction
  assign rd0[134:126] = \606 (banks[539:531], banks[530:504], { _058_, _057_, _056_ });
  assign _059_ = 5'h12 < head[4:0];
  assign _060_ = _059_ ? _021_ : head[6:5];
  function [8:0] \62 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \62  = b[8:0];
      3'b?1?:
        \62  = b[17:9];
      3'b1??:
        \62  = b[26:18];
      default:
        \62  = a;
    endcase
  endfunction
  assign rd0[287:279] = \62 (banks[1151:1143], banks[1142:1116], { _031_, _024_, _000_ });
  assign _061_ = ! _060_;
  assign _062_ = _060_ == 1'h1;
  assign _063_ = _060_ == 2'h2;
  function [8:0] \638 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \638  = b[8:0];
      3'b?1?:
        \638  = b[17:9];
      3'b1??:
        \638  = b[26:18];
      default:
        \638  = a;
    endcase
  endfunction
  assign rd0[125:117] = \638 (banks[503:495], banks[494:468], { _063_, _062_, _061_ });
  assign _064_ = 5'h13 < head[4:0];
  assign _043_ = 1'h1 < head[4:0];
  assign _066_ = _064_ ? _021_ : head[6:5];
  assign _067_ = ! _066_;
  assign _068_ = _066_ == 1'h1;
  assign _069_ = _066_ == 2'h2;
  function [8:0] \670 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \670  = b[8:0];
      3'b?1?:
        \670  = b[17:9];
      3'b1??:
        \670  = b[26:18];
      default:
        \670  = a;
    endcase
  endfunction
  assign rd0[116:108] = \670 (banks[467:459], banks[458:432], { _069_, _068_, _067_ });
  assign _070_ = 5'h14 < head[4:0];
  assign _071_ = _070_ ? _021_ : head[6:5];
  assign _073_ = ! _071_;
  assign _074_ = _071_ == 1'h1;
  assign _075_ = _071_ == 2'h2;
  function [8:0] \702 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \702  = b[8:0];
      3'b?1?:
        \702  = b[17:9];
      3'b1??:
        \702  = b[26:18];
      default:
        \702  = a;
    endcase
  endfunction
  assign rd0[107:99] = \702 (banks[431:423], banks[422:396], { _075_, _074_, _073_ });
  assign _076_ = 5'h15 < head[4:0];
  assign _077_ = _076_ ? _021_ : head[6:5];
  assign _078_ = ! _077_;
  assign _081_ = _077_ == 1'h1;
  assign _082_ = _077_ == 2'h2;
  function [8:0] \734 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \734  = b[8:0];
      3'b?1?:
        \734  = b[17:9];
      3'b1??:
        \734  = b[26:18];
      default:
        \734  = a;
    endcase
  endfunction
  assign rd0[98:90] = \734 (banks[395:387], banks[386:360], { _082_, _081_, _078_ });
  assign _083_ = 5'h16 < head[4:0];
  assign _084_ = _083_ ? _021_ : head[6:5];
  assign _065_ = _043_ ? _021_ : head[6:5];
  assign _085_ = ! _084_;
  assign _086_ = _084_ == 1'h1;
  assign _088_ = _084_ == 2'h2;
  function [8:0] \766 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \766  = b[8:0];
      3'b?1?:
        \766  = b[17:9];
      3'b1??:
        \766  = b[26:18];
      default:
        \766  = a;
    endcase
  endfunction
  assign rd0[89:81] = \766 (banks[359:351], banks[350:324], { _088_, _086_, _085_ });
  assign _089_ = 5'h17 < head[4:0];
  assign _090_ = _089_ ? _021_ : head[6:5];
  assign _091_ = ! _090_;
  assign _092_ = _090_ == 1'h1;
  assign _093_ = _090_ == 2'h2;
  function [8:0] \798 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \798  = b[8:0];
      3'b?1?:
        \798  = b[17:9];
      3'b1??:
        \798  = b[26:18];
      default:
        \798  = a;
    endcase
  endfunction
  assign rd0[80:72] = \798 (banks[323:315], banks[314:288], { _093_, _092_, _091_ });
  assign _094_ = 5'h18 < head[4:0];
  assign _095_ = _094_ ? _021_ : head[6:5];
  assign _096_ = ! _095_;
  assign _097_ = _095_ == 1'h1;
  assign _098_ = _095_ == 2'h2;
  function [8:0] \830 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \830  = b[8:0];
      3'b?1?:
        \830  = b[17:9];
      3'b1??:
        \830  = b[26:18];
      default:
        \830  = a;
    endcase
  endfunction
  assign rd0[71:63] = \830 (banks[287:279], banks[278:252], { _098_, _097_, _096_ });
  assign _100_ = 5'h19 < head[4:0];
  assign _101_ = _100_ ? _021_ : head[6:5];
  assign _072_ = ! _065_;
  assign _102_ = ! _101_;
  assign _103_ = _101_ == 1'h1;
  assign _104_ = _101_ == 2'h2;
  function [8:0] \862 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \862  = b[8:0];
      3'b?1?:
        \862  = b[17:9];
      3'b1??:
        \862  = b[26:18];
      default:
        \862  = a;
    endcase
  endfunction
  assign rd0[62:54] = \862 (banks[251:243], banks[242:216], { _104_, _103_, _102_ });
  assign _105_ = 5'h1a < head[4:0];
  assign _106_ = _105_ ? _021_ : head[6:5];
  assign _080_ = _065_ == 1'h1;
  assign _107_ = ! _106_;
  assign _108_ = _106_ == 1'h1;
  assign _109_ = _106_ == 2'h2;
  function [8:0] \894 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \894  = b[8:0];
      3'b?1?:
        \894  = b[17:9];
      3'b1??:
        \894  = b[26:18];
      default:
        \894  = a;
    endcase
  endfunction
  assign rd0[53:45] = \894 (banks[215:207], banks[206:180], { _109_, _108_, _107_ });
  assign _110_ = 5'h1b < head[4:0];
  assign _111_ = _110_ ? _021_ : head[6:5];
  assign _087_ = _065_ == 2'h2;
  assign _112_ = ! _111_;
  assign _113_ = _111_ == 1'h1;
  assign _114_ = _111_ == 2'h2;
  function [8:0] \926 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \926  = b[8:0];
      3'b?1?:
        \926  = b[17:9];
      3'b1??:
        \926  = b[26:18];
      default:
        \926  = a;
    endcase
  endfunction
  assign rd0[44:36] = \926 (banks[179:171], banks[170:144], { _114_, _113_, _112_ });
  assign _115_ = 5'h1c < head[4:0];
  assign _116_ = _115_ ? _021_ : head[6:5];
  function [8:0] \94 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \94  = b[8:0];
      3'b?1?:
        \94  = b[17:9];
      3'b1??:
        \94  = b[26:18];
      default:
        \94  = a;
    endcase
  endfunction
  assign rd0[278:270] = \94 (banks[1115:1107], banks[1106:1080], { _087_, _080_, _072_ });
  assign _117_ = ! _116_;
  assign _118_ = _116_ == 1'h1;
  assign _119_ = _116_ == 2'h2;
  function [8:0] \958 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \958  = b[8:0];
      3'b?1?:
        \958  = b[17:9];
      3'b1??:
        \958  = b[26:18];
      default:
        \958  = a;
    endcase
  endfunction
  assign rd0[35:27] = \958 (banks[143:135], banks[134:108], { _119_, _118_, _117_ });
  assign _120_ = 5'h1d < head[4:0];
  assign _099_ = 2'h2 < head[4:0];
  assign _122_ = _120_ ? _021_ : head[6:5];
  assign _123_ = ! _122_;
  assign _124_ = _122_ == 1'h1;
  assign _125_ = _122_ == 2'h2;
  function [8:0] \990 ;
    input [8:0] a;
    input [26:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        \990  = b[8:0];
      3'b?1?:
        \990  = b[17:9];
      3'b1??:
        \990  = b[26:18];
      default:
        \990  = a;
    endcase
  endfunction
  assign rd0[26:18] = \990 (banks[107:99], banks[98:72], { _125_, _124_, _123_ });
  assign _126_ = 5'h1e < head[4:0];
  assign BYTE_COUNT_o = count;
  assign FETCH_READY_o = ready;
  assign WINDOW_PC_o = head_pc;
  assign head_bits = head;
  assign rd5 = { WINDOW_FAULT_o[31], WINDOW_o[255:248], WINDOW_FAULT_o[30], WINDOW_o[247:240], WINDOW_FAULT_o[29], WINDOW_o[239:232], WINDOW_FAULT_o[28], WINDOW_o[231:224], WINDOW_FAULT_o[27], WINDOW_o[223:216], WINDOW_FAULT_o[26], WINDOW_o[215:208], WINDOW_FAULT_o[25], WINDOW_o[207:200], WINDOW_FAULT_o[24], WINDOW_o[199:192], WINDOW_FAULT_o[23], WINDOW_o[191:184], WINDOW_FAULT_o[22], WINDOW_o[183:176], WINDOW_FAULT_o[21], WINDOW_o[175:168], WINDOW_FAULT_o[20], WINDOW_o[167:160], WINDOW_FAULT_o[19], WINDOW_o[159:152], WINDOW_FAULT_o[18], WINDOW_o[151:144], WINDOW_FAULT_o[17], WINDOW_o[143:136], WINDOW_FAULT_o[16], WINDOW_o[135:128], WINDOW_FAULT_o[15], WINDOW_o[127:120], WINDOW_FAULT_o[14], WINDOW_o[119:112], WINDOW_FAULT_o[13], WINDOW_o[111:104], WINDOW_FAULT_o[12], WINDOW_o[103:96], WINDOW_FAULT_o[11], WINDOW_o[95:88], WINDOW_FAULT_o[10], WINDOW_o[87:80], WINDOW_FAULT_o[9], WINDOW_o[79:72], WINDOW_FAULT_o[8], WINDOW_o[71:64], WINDOW_FAULT_o[7], WINDOW_o[63:56], WINDOW_FAULT_o[6], WINDOW_o[55:48], WINDOW_FAULT_o[5], WINDOW_o[47:40], WINDOW_FAULT_o[4], WINDOW_o[39:32], WINDOW_FAULT_o[3], WINDOW_o[31:24], WINDOW_FAULT_o[2], WINDOW_o[23:16], WINDOW_FAULT_o[1], WINDOW_o[15:8], WINDOW_FAULT_o[0], WINDOW_o[7:0] };
  assign tail_index = tail_bits;
  assign wr0 = { FETCH_FAULT_i, FETCH_BLOCK_i[255:248], FETCH_FAULT_i, FETCH_BLOCK_i[247:240], FETCH_FAULT_i, FETCH_BLOCK_i[239:232], FETCH_FAULT_i, FETCH_BLOCK_i[231:224], FETCH_FAULT_i, FETCH_BLOCK_i[223:216], FETCH_FAULT_i, FETCH_BLOCK_i[215:208], FETCH_FAULT_i, FETCH_BLOCK_i[207:200], FETCH_FAULT_i, FETCH_BLOCK_i[199:192], FETCH_FAULT_i, FETCH_BLOCK_i[191:184], FETCH_FAULT_i, FETCH_BLOCK_i[183:176], FETCH_FAULT_i, FETCH_BLOCK_i[175:168], FETCH_FAULT_i, FETCH_BLOCK_i[167:160], FETCH_FAULT_i, FETCH_BLOCK_i[159:152], FETCH_FAULT_i, FETCH_BLOCK_i[151:144], FETCH_FAULT_i, FETCH_BLOCK_i[143:136], FETCH_FAULT_i, FETCH_BLOCK_i[135:128], FETCH_FAULT_i, FETCH_BLOCK_i[127:120], FETCH_FAULT_i, FETCH_BLOCK_i[119:112], FETCH_FAULT_i, FETCH_BLOCK_i[111:104], FETCH_FAULT_i, FETCH_BLOCK_i[103:96], FETCH_FAULT_i, FETCH_BLOCK_i[95:88], FETCH_FAULT_i, FETCH_BLOCK_i[87:80], FETCH_FAULT_i, FETCH_BLOCK_i[79:72], FETCH_FAULT_i, FETCH_BLOCK_i[71:64], FETCH_FAULT_i, FETCH_BLOCK_i[63:56], FETCH_FAULT_i, FETCH_BLOCK_i[55:48], FETCH_FAULT_i, FETCH_BLOCK_i[47:40], FETCH_FAULT_i, FETCH_BLOCK_i[39:32], FETCH_FAULT_i, FETCH_BLOCK_i[31:24], FETCH_FAULT_i, FETCH_BLOCK_i[23:16], FETCH_FAULT_i, FETCH_BLOCK_i[15:8], FETCH_FAULT_i, FETCH_BLOCK_i[7:0] };
  assign { wr1[287], wr1[278], wr1[269], wr1[260], wr1[251], wr1[242], wr1[233], wr1[224], wr1[215], wr1[206], wr1[197], wr1[188], wr1[179], wr1[170], wr1[161], wr1[152], wr1[143], wr1[134], wr1[125], wr1[116], wr1[107], wr1[98], wr1[89], wr1[80], wr1[71], wr1[62], wr1[53], wr1[44], wr1[35], wr1[26], wr1[17], wr1[8] } = { FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i };
  assign { wr2[287], wr2[278], wr2[269], wr2[260], wr2[251], wr2[242], wr2[233], wr2[224], wr2[215], wr2[206], wr2[197], wr2[188], wr2[179], wr2[170], wr2[161], wr2[152], wr2[143], wr2[134], wr2[125], wr2[116], wr2[107], wr2[98], wr2[89], wr2[80], wr2[71], wr2[62], wr2[53], wr2[44], wr2[35], wr2[26], wr2[17], wr2[8] } = { FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i };
  assign { wr3[287], wr3[278], wr3[269], wr3[260], wr3[251], wr3[242], wr3[233], wr3[224], wr3[215], wr3[206], wr3[197], wr3[188], wr3[179], wr3[170], wr3[161], wr3[152], wr3[143], wr3[134], wr3[125], wr3[116], wr3[107], wr3[98], wr3[89], wr3[80], wr3[71], wr3[62], wr3[53], wr3[44], wr3[35], wr3[26], wr3[17], wr3[8] } = { FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i };
  assign { wr4[287], wr4[278], wr4[269], wr4[260], wr4[251], wr4[242], wr4[233], wr4[224], wr4[215], wr4[206], wr4[197], wr4[188], wr4[179], wr4[170], wr4[161], wr4[152], wr4[143], wr4[134], wr4[125], wr4[116], wr4[107], wr4[98], wr4[89], wr4[80], wr4[71], wr4[62], wr4[53], wr4[44], wr4[35], wr4[26], wr4[17], wr4[8] } = { FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i };
  assign { wr5[287], wr5[278], wr5[269], wr5[260], wr5[251], wr5[242], wr5[233], wr5[224], wr5[215], wr5[206], wr5[197], wr5[188], wr5[179], wr5[170], wr5[161], wr5[152], wr5[143], wr5[134], wr5[125], wr5[116], wr5[107], wr5[98], wr5[89], wr5[80], wr5[71], wr5[62], wr5[53], wr5[44], wr5[35], wr5[26], wr5[17], wr5[8] } = { FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i, FETCH_FAULT_i };
endmodule
